import logging
from pathlib import Path

import pytest

from llmflow.cli import main
from llmflow.cli_utils import (
    HELLO_PIPELINE,
    HELLO_PROMPT,
    HELLO_REPLY_PROMPT,
    AI_INDEX_DOC,
    AI_OVERVIEW_DOC,
    AI_RULES_DOC,
    COPILOT_INSTRUCTIONS_DOC,
    LANGUAGE_QUICKREF_DOC,
    PROJECT_AUDITS_README,
    PROJECT_TODO,
    TUTORIAL_DOC,
    VSCODE_DOC,
    init_project as init_environment,
)


def test_cli_init_creates_hello_prompt(tmp_path, monkeypatch, caplog):
    caplog.set_level(logging.INFO)
    monkeypatch.chdir(tmp_path)

    main(["init"])

    prompt_path = tmp_path / "prompts" / "hello.gpt"
    assert prompt_path.exists()
    assert prompt_path.read_text(encoding="utf-8") == HELLO_PROMPT

    # second run should be idempotent
    main(["init"])
    assert prompt_path.read_text(encoding="utf-8") == HELLO_PROMPT


def test_init_environment_creates_files(tmp_path, caplog):
    caplog.set_level(logging.INFO)

    init_environment(tmp_path)

    prompt_path = tmp_path / "prompts" / "hello.gpt"
    reply_prompt_path = tmp_path / "prompts" / "reply.gpt"
    pipeline_path = tmp_path / "pipelines" / "hello-llmflow.yaml"
    output_dir = tmp_path / "output"
    docs_dir = tmp_path / "docs"
    ai_context_dir = docs_dir / "ai-context"

    tutorial_doc_path = docs_dir / "tutorial.md"
    language_quickref_path = docs_dir / "llmflow-language-quickref.md"
    ai_overview_path = ai_context_dir / "overview.md"
    ai_rules_path = ai_context_dir / "rules.md"
    ai_index_path = ai_context_dir / "index.md"

    assert prompt_path.read_text(encoding="utf-8") == HELLO_PROMPT
    assert reply_prompt_path.read_text(encoding="utf-8") == HELLO_REPLY_PROMPT
    assert pipeline_path.read_text(encoding="utf-8") == HELLO_PIPELINE
    assert output_dir.is_dir()

    assert tutorial_doc_path.read_text(encoding="utf-8") == TUTORIAL_DOC
    assert language_quickref_path.read_text(encoding="utf-8") == LANGUAGE_QUICKREF_DOC
    assert ai_overview_path.read_text(encoding="utf-8") == AI_OVERVIEW_DOC
    assert ai_rules_path.read_text(encoding="utf-8") == AI_RULES_DOC
    assert ai_index_path.read_text(encoding="utf-8") == AI_INDEX_DOC

    vscode_doc_path = docs_dir / "vscode.md"
    project_todo_path = tmp_path / "project" / "TODO.md"
    project_audits_readme_path = tmp_path / "project" / "audits" / "README.md"

    assert vscode_doc_path.read_text(encoding="utf-8") == VSCODE_DOC
    assert project_todo_path.read_text(encoding="utf-8") == PROJECT_TODO
    assert project_audits_readme_path.read_text(encoding="utf-8") == PROJECT_AUDITS_README

    # idempotency: second run should not change existing files
    init_environment(tmp_path)
    assert prompt_path.read_text(encoding="utf-8") == HELLO_PROMPT
    assert reply_prompt_path.read_text(encoding="utf-8") == HELLO_REPLY_PROMPT
    assert pipeline_path.read_text(encoding="utf-8") == HELLO_PIPELINE
    assert tutorial_doc_path.read_text(encoding="utf-8") == TUTORIAL_DOC
    assert language_quickref_path.read_text(encoding="utf-8") == LANGUAGE_QUICKREF_DOC
    assert ai_overview_path.read_text(encoding="utf-8") == AI_OVERVIEW_DOC
    assert ai_rules_path.read_text(encoding="utf-8") == AI_RULES_DOC
    assert ai_index_path.read_text(encoding="utf-8") == AI_INDEX_DOC
    # project/TODO.md must never be overwritten — it's hand-edited from first run
    project_todo_path.write_text("# my hand-edited TODO\n", encoding="utf-8")
    init_environment(tmp_path)
    assert project_todo_path.read_text(encoding="utf-8") == "# my hand-edited TODO\n"


def test_init_update_overwrites_generated_files(tmp_path):
    """--update overwrites files carrying the generated marker, leaves hand-edited files alone."""
    init_environment(tmp_path)

    quickref_path = tmp_path / "docs" / "llmflow-language-quickref.md"
    pipeline_path = tmp_path / "pipelines" / "hello-llmflow.yaml"

    # Simulate a hand-edited file (no generated marker)
    pipeline_path.write_text("# hand-edited pipeline\n", encoding="utf-8")

    # Simulate an outdated generated doc (has marker, stale content)
    quickref_path.write_text("<!-- Generated by sp init -->\n# OLD CONTENT\n", encoding="utf-8")

    init_environment(tmp_path, update=True)

    # Generated file should be refreshed to current content
    assert quickref_path.read_text(encoding="utf-8") == LANGUAGE_QUICKREF_DOC

    # Hand-edited file must not be touched
    assert pipeline_path.read_text(encoding="utf-8") == "# hand-edited pipeline\n"


def test_init_update_flag_via_cli(tmp_path, monkeypatch):
    """llmflow init --update works via the CLI entrypoint."""
    monkeypatch.chdir(tmp_path)
    main(["init"])

    quickref_path = tmp_path / "docs" / "llmflow-language-quickref.md"
    quickref_path.write_text("<!-- Generated by sp init -->\n# OLD\n", encoding="utf-8")

    main(["init", "--update"])

    assert quickref_path.read_text(encoding="utf-8") == LANGUAGE_QUICKREF_DOC


class TestHelloGptContract:
    """hello.gpt and reply.gpt must declare variable contracts parseable by the linter."""

    def test_hello_prompt_has_requires_header(self, tmp_path):
        """HELLO_PROMPT must have a ---...--- frontmatter with requires: listing language_count."""
        from llmflow.utils.linter import parse_prompt_header

        p = tmp_path / "hello.gpt"
        p.write_text(HELLO_PROMPT, encoding="utf-8")
        header = parse_prompt_header(str(p))
        assert header is not None, "HELLO_PROMPT has no parseable header"
        requires = header.get("requires", [])
        assert "language_count" in requires, (
            f"HELLO_PROMPT header must declare 'language_count' in requires, got: {requires}"
        )

    def test_reply_prompt_has_requires_header(self, tmp_path):
        """HELLO_REPLY_PROMPT must have a ---...--- frontmatter with requires: listing greeting_markdown."""
        from llmflow.utils.linter import parse_prompt_header

        p = tmp_path / "reply.gpt"
        p.write_text(HELLO_REPLY_PROMPT, encoding="utf-8")
        header = parse_prompt_header(str(p))
        assert header is not None, "HELLO_REPLY_PROMPT has no parseable header"
        requires = header.get("requires", [])
        assert "greeting_markdown" in requires, (
            f"HELLO_REPLY_PROMPT header must declare 'greeting_markdown' in requires, got: {requires}"
        )


class TestSpCliName:
    """All generated template content must reference 'sp' as the CLI command, not 'llmflow'."""

    def test_hello_pipeline_uses_sp_not_llmflow(self):
        """HELLO_PIPELINE description must say 'sp run', not 'llmflow run'."""
        assert "sp run" in HELLO_PIPELINE, (
            "HELLO_PIPELINE must reference 'sp run' — the CLI was renamed from 'llmflow' to 'sp'"
        )
        assert "llmflow run" not in HELLO_PIPELINE, (
            "HELLO_PIPELINE must not reference 'llmflow run' — the CLI was renamed to 'sp'"
        )

    def test_tutorial_doc_uses_sp_not_llmflow(self):
        """TUTORIAL_DOC must say 'sp run ...', not 'llmflow run ...'."""
        assert "sp run" in TUTORIAL_DOC, (
            "TUTORIAL_DOC must reference 'sp run' — the CLI was renamed from 'llmflow' to 'sp'"
        )
        assert "llmflow run" not in TUTORIAL_DOC, (
            "TUTORIAL_DOC must not reference 'llmflow run' — the CLI was renamed to 'sp'"
        )

    def test_language_quickref_uses_sp_not_llmflow(self):
        """LANGUAGE_QUICKREF_DOC must say 'sp run ...', not 'llmflow run ...'."""
        assert "sp run" in LANGUAGE_QUICKREF_DOC, (
            "LANGUAGE_QUICKREF_DOC must reference 'sp run'"
        )
        assert "llmflow run" not in LANGUAGE_QUICKREF_DOC, (
            "LANGUAGE_QUICKREF_DOC must not reference 'llmflow run'"
        )

    def test_copilot_instructions_uses_sp_not_llmflow(self):
        """COPILOT_INSTRUCTIONS_DOC must say 'sp lint/run ...', not 'llmflow lint/run ...'."""
        assert "llmflow run" not in COPILOT_INSTRUCTIONS_DOC, (
            "COPILOT_INSTRUCTIONS_DOC must not reference 'llmflow run'"
        )
        assert "llmflow lint" not in COPILOT_INSTRUCTIONS_DOC, (
            "COPILOT_INSTRUCTIONS_DOC must not reference 'llmflow lint'"
        )

    def test_generated_marker_uses_sp(self):
        """GENERATED_MARKER must reference 'sp init', not 'llmflow init'."""
        from llmflow.cli_utils import GENERATED_MARKER
        assert "sp init" in GENERATED_MARKER, (
            f"GENERATED_MARKER must say 'Generated by sp init', got: {GENERATED_MARKER!r}"
        )

    def test_project_todo_uses_sp(self):
        """PROJECT_TODO must not reference 'llmflow' as a CLI command."""
        assert "llmflow run" not in PROJECT_TODO, (
            "PROJECT_TODO must not reference 'llmflow run'"
        )

    def test_sp_entrypoint_in_pyproject(self):
        """pyproject.toml must define 'sp' as a console script entry point."""
        import tomllib
        from pathlib import Path
        pyproject = Path(__file__).parent.parent / "pyproject.toml"
        with open(pyproject, "rb") as f:
            data = tomllib.load(f)
        scripts = data.get("project", {}).get("scripts", {})
        assert "sp" in scripts, (
            f"pyproject.toml [project.scripts] must have 'sp' entry, got: {list(scripts.keys())}"
        )
        assert "llmflow" not in scripts, (
            "pyproject.toml [project.scripts] must not have old 'llmflow' entry"
        )


class TestAiContextDocsCoverGptFormat:
    """AI context docs must teach an LLM how to write .gpt variable contract headers."""

    def test_language_quickref_includes_requires_syntax(self):
        """LANGUAGE_QUICKREF_DOC must show 'requires:' so an AI knows to declare it."""
        assert "requires:" in LANGUAGE_QUICKREF_DOC, (
            "LANGUAGE_QUICKREF_DOC must include 'requires:' to teach .gpt contract syntax"
        )

    def test_ai_rules_doc_mentions_prompt_contract(self):
        """AI_RULES_DOC must reference 'requires' so the AI knows to declare prompt contracts."""
        assert "requires" in AI_RULES_DOC, (
            "AI_RULES_DOC must reference 'requires' so the AI knows to declare prompt contracts"
        )


class TestProjectTodoTutorial:
    """PROJECT_TODO must pre-populate with tutorial backlog items guiding new users
    through AI-assisted pipeline exploration and GitHub issue workflow."""

    def test_todo_has_run_command(self):
        """Backlog must show users how to run the hello pipeline."""
        assert "sp run" in PROJECT_TODO, (
            "PROJECT_TODO must include 'sp run' so users know how to run a pipeline"
        )

    def test_todo_has_copilot_explain(self):
        """Backlog must direct users to use Copilot /explain on the pipeline."""
        assert "/explain" in PROJECT_TODO, (
            "PROJECT_TODO must include '/explain' to guide AI-assisted exploration"
        )

    def test_todo_has_github_issues(self):
        """Backlog must reference GitHub issues as a workflow step."""
        assert "issue" in PROJECT_TODO.lower(), (
            "PROJECT_TODO must mention GitHub issues so users connect AI + issue workflow"
        )

    def test_todo_has_extend_step(self):
        """Backlog must prompt user to extend the pipeline with AI help."""
        assert "extend" in PROJECT_TODO.lower() or "implement" in PROJECT_TODO.lower(), (
            "PROJECT_TODO must include a step to extend or implement a new pipeline idea"
        )

    def test_todo_has_debug_step(self):
        """Backlog must include a debugging step with AI."""
        assert "debug" in PROJECT_TODO.lower() or "diagnose" in PROJECT_TODO.lower(), (
            "PROJECT_TODO must include a step for AI-assisted debugging"
        )


class TestHelloYaml:
    """hello.yaml must be created by llmflow init and pass full lint."""

    def test_init_creates_hello_yaml(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        main(["init"])
        assert (tmp_path / "pipelines" / "hello.yaml").exists()

    def test_hello_yaml_content_has_variables_block(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        main(["init"])
        import yaml

        content = yaml.safe_load(
            (tmp_path / "pipelines" / "hello.yaml").read_text(encoding="utf-8")
        )
        assert "variables" in content, "hello.yaml must have a variables: block"

    def test_hello_yaml_passes_lint(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        main(["init"])
        from llmflow.utils.linter import lint_pipeline_full

        result = lint_pipeline_full(str(tmp_path / "pipelines" / "hello.yaml"))
        assert result.valid, f"hello.yaml failed lint: {result.errors}"