"""Tests for sp context commands."""

import logging
from pathlib import Path

import pytest

from llmflow.context import list_context_files, extract_description


def test_list_context_files_returns_empty_when_dir_missing(tmp_path, caplog):
    """sp context list returns empty list when docs/ai-context/ doesn't exist."""
    caplog.set_level(logging.INFO)

    result = list_context_files(tmp_path)

    assert result == []


def test_list_context_files_returns_empty_when_dir_empty(tmp_path, caplog):
    """sp context list returns empty list when docs/ai-context/ is empty."""
    caplog.set_level(logging.INFO)

    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)

    result = list_context_files(tmp_path)

    assert result == []


def test_list_context_files_finds_markdown_files(tmp_path, caplog):
    """sp context list finds all .md files in docs/ai-context/."""
    caplog.set_level(logging.INFO)

    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)

    # Create some markdown files
    (ai_context_dir / "index.md").write_text("# Index\nMaster index")
    (ai_context_dir / "rules.md").write_text("# Rules\nAI behavior rules")
    (ai_context_dir / "basex-patterns.md").write_text("# BaseX Patterns\nXQuery examples")

    # Create a non-markdown file (should be ignored)
    (ai_context_dir / "notes.txt").write_text("Some notes")

    result = list_context_files(tmp_path)

    assert len(result) == 3
    filenames = [item["file"] for item in result]
    assert "index.md" in filenames
    assert "rules.md" in filenames
    assert "basex-patterns.md" in filenames
    assert "notes.txt" not in filenames


def test_list_context_files_includes_descriptions(tmp_path, caplog):
    """sp context list extracts descriptions from files."""
    caplog.set_level(logging.INFO)

    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)

    (ai_context_dir / "index.md").write_text("# Index\n\nMaster index of files")
    (ai_context_dir / "rules.md").write_text("# AI Behavior Rules\n\nRules for AI assistants")

    result = list_context_files(tmp_path)

    assert len(result) == 2

    # Find the index.md entry
    index_entry = next(item for item in result if item["file"] == "index.md")
    assert index_entry["description"] == "Master index of files"

    # Find the rules.md entry
    rules_entry = next(item for item in result if item["file"] == "rules.md")
    assert rules_entry["description"] == "Rules for AI assistants"


def test_list_context_files_sorted_alphabetically(tmp_path, caplog):
    """sp context list returns files sorted alphabetically."""
    caplog.set_level(logging.INFO)

    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)

    # Create files in non-alphabetical order
    (ai_context_dir / "zebra.md").write_text("# Zebra\nZ content")
    (ai_context_dir / "alpha.md").write_text("# Alpha\nA content")
    (ai_context_dir / "middle.md").write_text("# Middle\nM content")

    result = list_context_files(tmp_path)

    filenames = [item["file"] for item in result]
    assert filenames == ["alpha.md", "middle.md", "zebra.md"]


def test_extract_description_from_first_paragraph(tmp_path):
    """Extract description from first paragraph after heading."""
    content = """# My Document

This is the first paragraph with a description.

This is the second paragraph."""

    description = extract_description(content)
    assert description == "This is the first paragraph with a description."


def test_extract_description_handles_no_heading(tmp_path):
    """Extract description from first non-empty line if no heading."""
    content = """This is the first line.

This is the second paragraph."""

    description = extract_description(content)
    assert description == "This is the first line."


def test_extract_description_handles_empty_file(tmp_path):
    """Extract description returns empty string for empty file."""
    content = ""

    description = extract_description(content)
    assert description == ""


def test_extract_description_handles_comments_and_empty_lines(tmp_path):
    """Extract description skips HTML comments and empty lines."""
    content = """<!-- Generated by sp init -->
# My Document

The actual description here.

More content."""

    description = extract_description(content)
    assert description == "The actual description here."


def test_extract_description_truncates_long_descriptions(tmp_path):
    """Extract description truncates to reasonable length."""
    long_paragraph = "This is a very long paragraph. " * 20
    content = f"""# My Document

{long_paragraph}

More content."""

    description = extract_description(content)
    # Should truncate to ~100 chars
    assert len(description) <= 120
    assert description.endswith("...")


def test_extract_description_from_heading_only(tmp_path):
    """Extract description uses heading if no paragraph follows."""
    content = """# BaseX Query Patterns"""

    description = extract_description(content)
    assert description == "BaseX Query Patterns"


def test_list_context_files_handles_subdirectories(tmp_path, caplog):
    """sp context list ignores subdirectories, only reads top-level files."""
    caplog.set_level(logging.INFO)

    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)

    # Top-level files
    (ai_context_dir / "index.md").write_text("# Index\nMain index")

    # Subdirectory with files (should be ignored)
    subdir = ai_context_dir / "archived"
    subdir.mkdir()
    (subdir / "old.md").write_text("# Old\nOld content")

    result = list_context_files(tmp_path)

    assert len(result) == 1
    assert result[0]["file"] == "index.md"


def test_cli_context_list_command(tmp_path, monkeypatch, caplog):
    """Test sp context list CLI command."""
    from llmflow.cli import main

    caplog.set_level(logging.INFO)
    monkeypatch.chdir(tmp_path)

    # Create some context files
    ai_context_dir = tmp_path / "docs" / "ai-context"
    ai_context_dir.mkdir(parents=True)
    (ai_context_dir / "index.md").write_text("# Index\nMaster index")
    (ai_context_dir / "rules.md").write_text("# Rules\nAI rules")

    # Capture stdout
    import io
    import sys
    captured_output = io.StringIO()
    sys.stdout = captured_output

    try:
        main(["context", "list"])
        output = captured_output.getvalue()
    finally:
        sys.stdout = sys.__stdout__

    assert "AI Context Files" in output
    assert "index.md" in output
    assert "rules.md" in output
    assert "Master index" in output
    assert "AI rules" in output


def test_cli_context_list_empty_directory(tmp_path, monkeypatch, caplog):
    """Test sp context list with no context files."""
    from llmflow.cli import main

    caplog.set_level(logging.INFO)
    monkeypatch.chdir(tmp_path)

    # Capture stdout
    import io
    import sys
    captured_output = io.StringIO()
    sys.stdout = captured_output

    try:
        main(["context", "list"])
        output = captured_output.getvalue()
    finally:
        sys.stdout = sys.__stdout__

    assert "No AI context files found" in output
    assert "sp init" in output
