"""Tests for the managed-file catalog (#204, plan D7).

D7 ruled out marker-sniffing. `sp init --update` decided ownership by looking for
`<!-- Generated by sp init -->` on line 1, and that marker text had *already* drifted in
shipped code — `cli.py:118-122` advertises `llmflow init` while the constant at
`cli_utils.py:568` says `sp init`. The Captain: *"Relying on this marker is fragile. We
need a catalog that says what files sp init works on. We have already had failures when
subsequent versions of our software changed the exact text in that string."*

Ownership therefore becomes a property of a catalog entry keyed by **path**, never a
string inside the file.

Captain, 2026-08-18: *".claude files belong in the catalog too, so we don't lose sight of
them."*

These tests pin the two things the catalog exists to make *derivable* rather than
hand-maintained in a second place:

- the generated `.gitignore` (D9)
- `sp doctor`'s ownership boundary (D10)

Both are the same principle the Captain stated for D10: one authoritative place per fact.
"""

from pathlib import Path

import pytest
import yaml

from llmflow.file_catalog import Entry, Policy, Scope, Source, entries


def _templates() -> Path:
    import llmflow

    return Path(llmflow.__file__).parent / "templates"


def _by_path() -> dict[str, Entry]:
    return {e.path: e for e in entries()}


def test_catalog_is_not_empty():
    assert entries(), "the catalog is the ownership record; an empty one owns nothing"


def test_the_catalog_is_data_not_code():
    """Captain, 2026-08-19: *"a file catalog is data, not embedded in code. let's be
    declarative and get it right, don't embed data in code."*

    The first implementation built the entries as Python literals inside
    `file_catalog.py`. In a project whose whole premise is declarative YAML, the catalog
    belongs in a data file that can be read and edited without reading code.

    `file_catalog.py` is a loader. If the data file is gone, nothing is silently assumed.
    """
    from llmflow.file_catalog import catalog_path

    path = catalog_path()
    assert path.is_file(), f"the catalog data file is missing: {path}"
    assert path.suffix in (".yaml", ".yml"), "the catalog must be declarative data"

    declared = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert declared.get("files"), "no files declared in the catalog"
    assert declared.get("groups"), "no groups declared in the catalog"

    module = Path(__import__("llmflow.file_catalog", fromlist=["_"]).__file__)
    source = module.read_text(encoding="utf-8")
    for path_literal in (".cursorrules", "docs/ai-context/index.md", "disciplines/"):
        assert f'"{path_literal}"' not in source and f"'{path_literal}'" not in source, (
            f"{path_literal!r} is hardcoded in the loader; it belongs in the data file"
        )


def test_a_missing_catalog_fails_loudly():
    """Ownership cannot be guessed. If the data file is absent, say so and stop."""
    from llmflow import file_catalog

    original = file_catalog.catalog_path
    file_catalog.catalog_path = lambda: Path("/nonexistent/file-catalog.yaml")
    try:
        with pytest.raises(FileNotFoundError):
            file_catalog.entries()
    finally:
        file_catalog.catalog_path = original


def test_every_entry_declares_the_four_fields_d7_requires():
    """D7: 'path, policy, whether it is committed or ignored, and its source'."""
    for entry in entries():
        assert entry.path, "an entry without a path cannot key anything"
        assert isinstance(entry.policy, Policy)
        assert isinstance(entry.scope, Scope)
        assert isinstance(entry.source, Source)
        assert isinstance(entry.committed, bool)


def test_paths_are_unique():
    """The catalog is keyed by path. Two entries for one path means ownership is ambiguous."""
    paths = [e.path for e in entries()]
    duplicates = {p for p in paths if paths.count(p) > 1}
    assert not duplicates, f"duplicate catalog entries: {sorted(duplicates)}"


def test_claude_skills_are_catalogued():
    """Captain's D7 ruling: .claude files belong in the catalog so none are lost sight of."""
    claude_entries = [
        e for e in entries() if e.path.startswith(".claude/") and e.scope is Scope.PROJECT
    ]
    assert claude_entries, ".claude/ files are absent from the catalog"

    skill_entries = [e for e in claude_entries if e.path.startswith(".claude/skills/")]
    assert skill_entries, "the D1-A' skills copy is not catalogued"


def test_project_skills_are_committed_not_ignored():
    """D1-A': a fresh clone must get skills, so they cannot be gitignored.

    This is the whole point of the ruling — a clone with ignored skills has no slash
    commands, which is the failure #204 exists to remove.
    """
    for entry in entries():
        if entry.path.startswith(".claude/skills/"):
            assert entry.committed, f"{entry.path} is ignored; a clone would not receive it"


def test_gitignore_is_derived_from_the_catalog_not_a_second_list():
    """D9 + D7: the ignore list is a *consequence* of catalog entries.

    A hand-maintained .gitignore is exactly the second place a fact can live, and the
    class of drift D10 was ruled to stop.
    """
    from llmflow.file_catalog import project_gitignore_lines

    lines = project_gitignore_lines()
    assert lines, "no ignore lines derived from the catalog"

    ignored = {e.path for e in entries() if e.scope is Scope.PROJECT and not e.committed}
    for path in ignored:
        assert any(path in line for line in lines), f"{path} is uncommitted but not ignored"

    committed = {e.path for e in entries() if e.scope is Scope.PROJECT and e.committed}
    for path in committed:
        assert path not in lines, f"{path} is committed but appears in .gitignore"


def test_doctor_ownership_is_read_from_the_catalog():
    """D10: the ownership table and the catalog's policy field are the same information.

    Deriving one from the other is what stops them disagreeing.
    """
    from llmflow.file_catalog import managed_by_doctor

    managed = {e.path for e in managed_by_doctor()}
    assert managed, "doctor manages nothing; the boundary is not derived"

    for entry in managed_by_doctor():
        assert entry.policy is Policy.GENERATED, (
            f"{entry.path} is repaired by doctor but is not policy=generated"
        )


def test_user_context_and_claude_md_are_never_repaired():
    """D10's 'never touched' column, pinned so a later edit cannot quietly widen ownership."""
    from llmflow.file_catalog import managed_by_doctor

    managed = {e.path for e in managed_by_doctor()}
    assert "CLAUDE.md" not in managed
    for path in managed:
        assert not path.startswith("user-context/"), (
            f"{path}: user-context is the machine owner's, not sp's (D6)"
        )


def test_sp_owned_context_files_are_generated():
    """The four sp-generated docs/ai-context files are ours and are restored on drift."""
    catalog = _by_path()
    for name in ("sp/index.md", "sp/rules.md", "sp/github-workflow.md", "sp/overview.md"):
        entry = catalog.get(f"docs/ai-context/{name}")
        assert entry is not None, f"docs/ai-context/{name} is not catalogued"
        assert entry.policy is Policy.GENERATED, f"docs/ai-context/{name} should be sp-owned"


def test_disciplines_derive_from_shipped_templates():
    """Adding a template must not require editing the catalog by hand.

    This is the same rule doctor already follows. A second hardcoded list is how three
    disciplines went unshipped for months (#204, #181).
    """
    shipped = {p.name for p in (_templates() / "sp" / "disciplines").glob("*.md")}
    catalogued = {
        Path(e.path).name
        for e in entries()
        if e.scope is Scope.SP_HOME and e.path.startswith("disciplines/")
    }
    assert shipped, "the package ships no disciplines; this build looks incomplete"
    assert shipped == catalogued, (
        f"catalog and templates disagree — only in catalog: {catalogued - shipped}; "
        f"only shipped: {shipped - catalogued}"
    )


def test_skills_derive_from_shipped_templates():
    shipped = {p.name for p in (_templates() / "sp" / "skills").iterdir() if (p / "SKILL.md").exists()}
    catalogued = {
        Path(e.path).parts[1]
        for e in entries()
        if e.scope is Scope.SP_HOME and e.path.startswith("skills/")
    }
    assert shipped, "the package ships no skills"
    assert shipped == catalogued, (
        f"catalog and shipped skills disagree — only in catalog: {catalogued - shipped}; "
        f"only shipped: {shipped - catalogued}"
    )


def test_every_entry_resolves_to_real_shipped_content():
    """An entry naming a constant or template that does not exist owns nothing.

    Written after the first draft of the catalog named `AI_GITHUB_WORKFLOW_DOC`, which
    does not exist — the constant is `GITHUB_WORKFLOW_DOC`. Silent `getattr` misses are
    the same class of failure as the drifting marker string D7 replaced: the catalog
    would claim ownership of a file it could never restore.
    """
    from llmflow.file_catalog import Source, shipped_content, shipped_path

    for entry in entries():
        if entry.source is Source.TEMPLATE:
            assert shipped_path(entry) is not None, (
                f"{entry.path} names template {entry.template!r}, which is not shipped"
            )
        elif entry.source is Source.CONSTANT:
            assert shipped_content(entry) is not None, (
                f"{entry.path} names constant {entry.constant!r}, which does not exist"
            )


@pytest.mark.parametrize(
    "path",
    [
        ".cursorrules",
        ".windsurfrules",
        ".github/copilot-instructions.md",
    ],
)
def test_assistant_rule_files_are_catalogued(path: str):
    """D4/A2: these are now written unconditionally, so they are managed files."""
    assert path in _by_path(), f"{path} is written by sp init but not catalogued"
