"""Machine-readable catalog of the public API's methods (LLMFlow#187, Decision 2).

The *attribute* surface is described by ``PIPELINE_SCHEMA``; this catalog covers the
*verbs* — the computed operations the schema cannot describe. It is generated by
introspection, so it cannot drift from the actual methods.
"""
from __future__ import annotations

import inspect
from typing import Any, Callable, Dict, List


def _signature(fn: Callable[..., Any]) -> str:
    params = [
        str(p)
        for name, p in inspect.signature(fn).parameters.items()
        if name not in ("self", "cls")
    ]
    return "(" + ", ".join(params) + ")"


def _entry(node: str, name: str, fn: Callable[..., Any]) -> Dict[str, Any]:
    return {
        "node": node,
        "name": name,
        "signature": name + _signature(fn),
        "doc": (inspect.getdoc(fn) or "").split("\n", 1)[0],
    }


def api_catalog() -> List[Dict[str, Any]]:
    """Return the public API's methods as ``{node, name, signature, doc}`` entries.

    Covers the computed operations on ``Pipeline`` / ``Step`` and the module-level
    functions. Attribute accessors are described by ``PIPELINE_SCHEMA``, not here.
    """
    from llmflow.model import Pipeline, Step, load_pipeline

    entries: List[Dict[str, Any]] = []
    for node_name, cls in (("Pipeline", Pipeline), ("Step", Step)):
        for name, member in sorted(vars(cls).items()):
            if not name.startswith("_") and inspect.isfunction(member):
                entries.append(_entry(node_name, name, member))

    entries.append(_entry("llmflow", "load_pipeline", load_pipeline))
    from llmflow.utils.llm_runner import call_llm

    entries.append(_entry("llmflow", "call_llm", call_llm))
    return entries
