import sys
import signal
from pathlib import Path

logger = None  # Initialized after Logger singleton is available


def _cli_sigint_handler(signum, frame):
    """Handle Ctrl+C at the CLI process level."""
    msg1 = "\n⚠️  Execution interrupted by user (Ctrl+C)"
    msg2 = "   Pipeline stopped."
    if logger is not None:
        logger.info(msg1)
        logger.info(msg2)
    else:
        sys.stderr.write(f"{msg1}\n{msg2}\n")
        sys.stderr.flush()
    sys.exit(130)


signal.signal(signal.SIGINT, _cli_sigint_handler)


import argparse
import json
import os
from pathlib import Path

from llmflow.modules.logger import Logger

# Following the Logger Pattern guideline: use the shared Logger()
# singleton so CLI messages go to both console and llmflow.log.
logger = Logger()


try:
    from importlib.metadata import version
    __version__ = version("llmflow")
except Exception:
    __version__ = "unknown"

from llmflow.runner import run_pipeline
from llmflow.cli_utils import init_project, list_pipelines

def list_pipelines(directory: str) -> list[str]:
    """List all YAML pipeline files in a directory."""
    base = Path(directory)
    if not base.exists():
        return []
    pipelines: list[str] = []
    for pattern in ("*.yaml", "*.yml"):
        for path in base.rglob(pattern):
            if path.is_file():
                pipelines.append(str(path.relative_to(base)))
    return sorted(dict.fromkeys(pipelines))


def build_parser():
    parser = argparse.ArgumentParser(prog="llmflow", description="LLMFlow CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # run command
    run_p = subparsers.add_parser("run", help="Run a pipeline")
    run_p.add_argument("--pipeline", required=True, help="Path to pipeline YAML")
    run_p.add_argument("--var", action="append", default=[], help="Pipeline variables key=value")
    run_p.add_argument("--dry-run", action="store_true", help="Dry run (no LLM calls)")
    run_p.add_argument("--skip-lint", action="store_true", help="Skip linting")
    run_p.add_argument("-v", "--verbose", action="store_true", help="Verbose logging")
    run_p.add_argument("--log", default="llmflow.log", help="Path to log file (default: llmflow.log in cwd)")
    run_p.add_argument("--rewind-to", help="Replay checkpoints up to and including this step name")
    run_p.add_argument("--stop-after", help="Stop pipeline after this step name runs")

    # list command
    list_p = subparsers.add_parser("list", help="List available pipelines")
    list_p.add_argument("--dir", default="pipelines", help="Directory to scan")
    list_p.add_argument("--json", action="store_true", help="Emit JSON output")

    # lint command
    lint_p = subparsers.add_parser("lint", help="Validate (lint) a pipeline without executing")
    lint_p.add_argument("--pipeline", required=True, help="Path to pipeline YAML")
    lint_p.add_argument("--var", action="append", default=[], help="Pipeline variables key=value")
    lint_p.add_argument("--fix-paths", action="store_true", help="Attempt simple path normalizations")
    lint_p.add_argument("--json", action="store_true", help="Emit JSON result")
    lint_p.add_argument("-v", "--verbose", action="store_true", help="Verbose logging")
    lint_p.add_argument("--rewind-to", help="Validate rewind readiness up to this step")

    # version command
    subparsers.add_parser("version", help="Show version")

    # gui command
    gui_p = subparsers.add_parser("gui", help="Launch web-based GUI")
    gui_p.add_argument("--host", default="127.0.0.1", help="Host address (default: 127.0.0.1)")
    gui_p.add_argument("--port", type=int, default=5000, help="Port number (default: 5000)")
    gui_p.add_argument("--no-browser", action="store_true", help="Don't auto-open browser")

    init_p = subparsers.add_parser("init", help="Create a starter LLMFlow environment")
    init_p.add_argument(
        "--update",
        action="store_true",
        help="Regenerate files that carry the '<!-- Generated by llmflow init -->' marker, leaving hand-edited files untouched",
    )
    init_p.add_argument(
        "--sync",
        action="store_true",
        help="Copy ai-context files from the installed LLMFlow package to the current project",
    )

    setup_p = subparsers.add_parser("setup", help="Configure AI provider API keys")
    setup_p.add_argument(
        "--update",
        action="store_true",
        help="Re-run setup to update keys or add new providers",
    )

    subparsers.add_parser("models", help="List available models by provider")
    subparsers.add_parser("update-ai-context", help="Regenerate docs/ai-context/ helper files for AI assistants")

    # download-data command
    dl_p = subparsers.add_parser("download-data", help="Download biblical reference datasets")
    dl_p.add_argument("dataset", nargs="?", default=None, help="Dataset name (e.g. macula-greek)")
    dl_p.add_argument("--list", action="store_true", help="List available datasets")
    dl_p.add_argument("--dest", default=None, help="Download destination (default: ~/.sp/data/)")

    # load-db command
    ldb_p = subparsers.add_parser("load-db", help="Load a downloaded dataset into a database (basex, ...)")
    ldb_p.add_argument("driver", nargs="?", default=None, help="Database driver (e.g. basex)")
    ldb_p.add_argument("dataset", nargs="?", default=None, help="Dataset key (e.g. acai, macula-greek)")
    ldb_p.add_argument("--name", default=None, dest="db_name", help="Override database name (default: dataset key)")
    ldb_p.add_argument("--force", action="store_true", help="Drop and recreate database if it already exists")
    ldb_p.add_argument("--source", default=None, help="Load from this path instead of ~/.sp/data/<dataset>/")
    ldb_p.add_argument("--list-drivers", action="store_true", dest="list_drivers", help="List available database drivers")
    ldb_p.add_argument("--register", action="store_true", help="Register database in global registry (~/.sp/)")

    # registry command
    reg_p = subparsers.add_parser("registry", help="Manage global resource registry (~/.sp/)")
    reg_sub = reg_p.add_subparsers(dest="registry_command", required=True)

    # registry list
    reg_list = reg_sub.add_parser("list", help="List registered resources")
    reg_list.add_argument("type", nargs="?", choices=["projects", "datasets", "databases"],
                         help="Resource type to list (default: all)")
    reg_list.add_argument("--json", action="store_true", help="Output as JSON")

    # registry info
    reg_info = reg_sub.add_parser("info", help="Show detailed info about a resource")
    reg_info.add_argument("type", choices=["project", "dataset", "database"], help="Resource type")
    reg_info.add_argument("id", help="Resource ID/name")

    # registry status
    reg_sub.add_parser("status", help="Show registry status and location")

    # registry context
    reg_sub.add_parser("context", help="Generate AI context from registry")

    # context command
    ctx_p = subparsers.add_parser("context", help="Manage AI context files (docs/ai-context/)")
    ctx_sub = ctx_p.add_subparsers(dest="context_command", required=True)

    # context list
    ctx_sub.add_parser("list", help="List available AI context files")

    # context add
    ctx_add = ctx_sub.add_parser("add", help="Register AI context file in global registry")
    ctx_add.add_argument("file", help="Context filename (e.g., basex-patterns.md)")
    ctx_add.add_argument("--description", required=True, help="Brief description of content")
    ctx_add.add_argument("--topics", required=True, help="Comma-separated topics (e.g., basex,xquery,greek)")
    ctx_add.add_argument("--project", help="Project name (default: current directory name)")
    ctx_add.add_argument("--path", help="Full path to file (default: docs/ai-context/<file>)")

    # context search
    ctx_search = ctx_sub.add_parser("search", help="Search AI context registry by topic")
    ctx_search.add_argument("topics", nargs="+", help="Topics to search for (matches any)")
    ctx_search.add_argument("--project", help="Filter by project name")

    # Standard --version flag (e.g. used by CI smoke tests: llmflow --version)
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    return parser


def _collect_cli_variables(pairs):
    variables = {}
    for item in pairs:
        if "=" not in item:
            raise ValueError(f"Invalid --var '{item}' (must be key=value)")
        k, v = item.split("=", 1)
        variables[k.strip()] = v.strip()
    return variables


def command_lint(
    pipeline_path: str,
    fix_paths: bool,
    json_mode: bool,
    verbose: bool,
    cli_vars: dict | None = None,
    rewind_to: str | None = None,
):
    from llmflow.utils.linter import lint_pipeline_full

    if verbose:
        print(f"🔍 Linting pipeline: {pipeline_path}")

    result = lint_pipeline_full(
        pipeline_path,
        vars=cli_vars,
        rewind_to=rewind_to,
    )

    if json_mode:
        output = {
            "pipeline": pipeline_path,
            "valid": result.valid,
            "errors": result.errors,
            "warnings": result.warnings,
        }
        print(json.dumps(output, ensure_ascii=False, indent=2))
    else:
        if result.valid:
            print("✅ Pipeline OK")
        else:
            print("❌ Pipeline has errors")
            if result.errors:
                print("Errors:")
                for e in result.errors:
                    print(f"  - {e}")
            if result.warnings:
                print("Warnings:")
                for w in result.warnings:
                    print(f"  - {w}")

    if not result.valid:
        sys.exit(1)


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "version":
        print(__version__)
        return

    if args.command == "gui":
        try:
            from llmflow.gui.server import start_server
        except ImportError:
            logger.error("❌ GUI dependencies not installed")
            logger.error("   Install with: pip install llmflow[gui]")
            sys.exit(1)

        start_server(
            host=args.host,
            port=args.port,
            open_browser=not args.no_browser
        )
        return

    if args.command == "list":
        pipelines = list_pipelines(args.dir)
        if args.json:
            print(json.dumps(pipelines, ensure_ascii=False, indent=2))
        else:
            for pipeline in pipelines:
                print(pipeline)
        return

    if args.command == "lint":
        variables = _collect_cli_variables(args.var)
        command_lint(
            args.pipeline,
            args.fix_paths,
            args.json,
            args.verbose,
            cli_vars=variables,
            rewind_to=args.rewind_to,
        )
        return

    if args.command == "init":
        from llmflow.cli_utils import sync_ai_context_files
        init_project(Path.cwd(), update=getattr(args, "update", False))
        if getattr(args, "sync", False):
            sync_ai_context_files(Path.cwd())
        return

    if args.command == "setup":
        from llmflow.setup_command import run_setup
        run_setup(update=getattr(args, "update", False))
        return

    if args.command == "models":
        from llmflow.setup_command import run_models
        run_models()
        return

    if args.command == "update-ai-context":
        import importlib.util
        _script = Path(__file__).resolve().parents[2] / "tools" / "update_ai_context.py"
        spec = importlib.util.spec_from_file_location("update_ai_context", _script)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.main()
        return

    if args.command == "download-data":
        from llmflow.download_data import run_download_data
        run_download_data(
            dataset=args.dataset,
            dest=args.dest,
            list_only=args.list,
        )
        return

    if args.command == "load-db":
        from llmflow.load_db import run_load_db
        run_load_db(
            driver=args.driver,
            dataset=args.dataset,
            db_name=args.db_name,
            force=args.force,
            source=args.source,
            list_drivers_only=args.list_drivers,
        )
        # TODO: If --register flag is set, register the database in registry
        return

    if args.command == "registry":
        from llmflow.registry import Registry
        registry = Registry()

        if args.registry_command == "list":
            # List registered resources
            if args.type == "projects" or args.type is None:
                projects = registry.projects.list()
                if args.json:
                    print(json.dumps({"projects": projects}, indent=2))
                elif projects:
                    print("Registered Projects:")
                    for p in projects:
                        desc = f" - {p.get('description', '')}" if p.get('description') else ""
                        print(f"  {p['name']:20s} {p['path']}{desc}")
                elif args.type == "projects":
                    print("No projects registered")

            if args.type == "datasets" or args.type is None:
                datasets = registry.datasets.list()
                if args.json:
                    print(json.dumps({"datasets": datasets}, indent=2))
                elif datasets:
                    print("\nAvailable Datasets:")
                    for ds in datasets:
                        print(f"  {ds['id']:25s} v{ds['version']:12s} {ds['format']:6s} {ds['path']}")
                elif args.type == "datasets":
                    print("No datasets registered")

            if args.type == "databases" or args.type is None:
                databases = registry.databases.list()
                if args.json:
                    print(json.dumps({"databases": databases}, indent=2))
                elif databases:
                    print("\nAvailable Databases:")
                    for db in databases:
                        if db['type'] == 'basex':
                            location = f"{db.get('host', 'localhost')}:{db.get('port', 1984)}"
                            print(f"  {db['name']:20s} BaseX at {location}")
                        elif db['type'] == 'duckdb':
                            print(f"  {db['name']:20s} DuckDB at {db.get('path', 'unknown')}")
                        else:
                            print(f"  {db['name']:20s} {db['type']}")
                elif args.type == "databases":
                    print("No databases registered")

        elif args.registry_command == "info":
            # Show detailed info about a resource
            if args.type == "project":
                resource = registry.projects.get(args.id)
                resource_type = "Project"
            elif args.type == "dataset":
                resource = registry.datasets.get(args.id)
                resource_type = "Dataset"
            elif args.type == "database":
                resource = registry.databases.get(args.id)
                resource_type = "Database"

            if resource is None:
                print(f"❌ {resource_type} '{args.id}' not found in registry")
                sys.exit(1)

            print(f"{resource_type}: {args.id}")
            print("=" * 60)
            for key, value in resource.items():
                print(f"{key:20s}: {value}")

        elif args.registry_command == "status":
            # Show registry status
            print(f"Registry Location: {registry.path}")
            print(f"Projects:  {len(registry.projects.list())}")
            print(f"Datasets:  {len(registry.datasets.list())}")
            print(f"Databases: {len(registry.databases.list())}")

        elif args.registry_command == "context":
            # Generate AI context
            print(registry.generate_ai_context())

        return

    if args.command == "context":
        from llmflow.context import list_context_files, format_context_list

        if args.context_command == "list":
            # List AI context files in docs/ai-context/
            cwd = Path.cwd()
            context_files = list_context_files(cwd)
            output = format_context_list(context_files)
            print(output)

        elif args.context_command == "add":
            # Register AI context file in global registry
            from llmflow.registry import Registry

            registry = Registry()

            # Determine project name
            project_name = args.project
            if not project_name:
                project_name = Path.cwd().name

            # Determine full path
            file_path = args.path
            if not file_path:
                file_path = str(Path.cwd() / "docs" / "ai-context" / args.file)

            # Parse topics
            topics = [t.strip() for t in args.topics.split(",")]

            # Register
            registry.ai_context.register(
                file=args.file,
                project=project_name,
                description=args.description,
                topics=topics,
                path=file_path
            )

            print(f"✅ Registered {args.file} in global AI context registry")
            print(f"   Project: {project_name}")
            print(f"   Topics: {', '.join(topics)}")

        elif args.context_command == "search":
            # Search AI context registry by topics
            from llmflow.registry import Registry

            registry = Registry()

            # Search
            results = registry.ai_context.search(
                topics=args.topics,
                project=args.project
            )

            if not results:
                print("No AI context files found matching search criteria.")
                if args.project:
                    print(f"  Project filter: {args.project}")
                print(f"  Topics: {', '.join(args.topics)}")
            else:
                print(f"Found {len(results)} AI context file(s):\n")
                for ctx in results:
                    topics_str = ", ".join(ctx.get("topics", []))
                    print(f"  {ctx['file']}")
                    print(f"    Project: {ctx.get('project', 'unknown')}")
                    print(f"    Description: {ctx.get('description', 'No description')}")
                    print(f"    Topics: {topics_str}")
                    if ctx.get('path'):
                        print(f"    Path: {ctx['path']}")
                    print()

        return

    if args.command == "run":
        try:
            variables = _collect_cli_variables(args.var)
            if not args.skip_lint:
                from llmflow.utils.linter import lint_pipeline_full

                logger.info("🔍 Validating pipeline...")
                try:
                    result = lint_pipeline_full(
                        args.pipeline,
                        vars=variables,
                        rewind_to=args.rewind_to,
                    )
                except FileNotFoundError as e:
                    logger.error(f"❌ Pipeline file not found: {args.pipeline}")
                    logger.error(f"   Current directory: {os.getcwd()}")
                    logger.error("   💡 Tip: Make sure you're running from the correct directory")
                    sys.exit(1)

                if not result.valid:
                    logger.error("❌ Pipeline validation failed:")
                    for error in result.errors:
                        logger.error(f"  - {error}")
                    sys.exit(1)

            try:
                run_pipeline(
                    args.pipeline,
                    vars=variables,
                    dry_run=args.dry_run,
                    verbose=args.verbose,
                    log_file=args.log,
                    rewind_to=args.rewind_to,
                    stop_after=args.stop_after,
                )
            except FileNotFoundError as e:
                logger.error(f"❌ Pipeline file not found: {args.pipeline}")
                logger.error(f"   Current directory: {os.getcwd()}")
                logger.error("   💡 Tip: Make sure you're running from the correct directory")
                sys.exit(1)
        except KeyboardInterrupt:
            logger.info("\n⚠️  Execution interrupted by user (Ctrl+C)")
            logger.info("   Pipeline stopped.")
            sys.exit(130)  # Standard exit code for SIGINT
        except BrokenPipeError:
            # Output was piped to a command that closed (e.g., head, less)
            # This is normal behavior, exit quietly
            sys.exit(0)
        except PermissionError as e:
            logger.error(f"❌ Permission denied: {e}")
            logger.error("   💡 Tip: Check file/directory permissions")
            sys.exit(1)
        return

    parser.print_help()


if __name__ == "__main__":
    main()
