"""CLI utility functions for LLMFlow project initialization."""
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

HELLO_PROMPT = """---
requires:
  - language_count
optional: []
format: Markdown
description: Generate a multilingual greeting list for {language_count} languages.
---
system: |
  You are a friendly assistant who showcases multilingual greetings.
user: |
  Pick {{language_count}} languages randomly.
  For each one, identify the language in English, share a native-script greeting, and add a short cultural note.
  Respond as a markdown bullet list.
"""

HELLO_REPLY_PROMPT = """---
requires:
  - greeting_markdown
optional: []
format: Markdown
description: Reply to the {greeting_markdown} bullet list with cultural notes.
---
system: |
  You are a cultural etiquette coach who replies warmly to multilingual greetings.
user: |
  You received this markdown list of greetings:

  {{greeting_markdown}}

  For each bullet, craft a short reply in the same language (when appropriate) plus an English explanation of the cultural nuance you appreciated. Return markdown with the same bullet structure.
"""

HELLO_PIPELINE = """name: "Hello Multilingual Pipeline"
description: |
  Sample pipeline generated by `sp init`.
  Run it with:
    sp run --pipeline pipelines/hello-llmflow.yaml
variables:
  prompts_dir: "prompts"
  output_dir: "output"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 500

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    outputs: greeting
    saveas:
      path: "${output_dir}/hello.md"

  - name: "respond-to-greetings"
    type: "llm"
    prompt:
      file: "reply.gpt"
      inputs:
        greeting_markdown: "${greeting}"
    outputs: reply_block
    saveas:
      path: "${output_dir}/responses.md"
"""

HELLO_YAML = """name: "Hello LLMFlow"
description: |
  Minimal starter pipeline for LLMFlow.
  Run with: sp run --pipeline pipelines/hello.yaml
variables:
  output_dir: "output"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 500

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    outputs: greeting
    saveas:
      path: "${output_dir}/greeting.md"
"""

TUTORIAL_DOC = """# LLMFlow Project Tutorial

This repository was initialized with `sp init`.
It includes a minimal, working example that shows how to declare variables,
pass them between steps, and write results to files using `saveas`.

## 1. Project layout

After running `sp init` in an empty directory, you should see:

```
./
├── output/
├── pipelines/
│   └── hello-llmflow.yaml
└── prompts/
    ├── hello.gpt
    └── reply.gpt
```

Pipelines live under `pipelines/`, prompt templates live under `prompts/`,
and generated content is written into `output/`.

## 2. Tutorial pipeline

The tutorial pipeline is defined in `pipelines/hello-llmflow.yaml`:

```yaml
name: "Hello Multilingual Pipeline"
variables:
  prompts_dir: "prompts"
  output_dir: "output"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.2

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    outputs: greeting
    saveas:
      path: "${output_dir}/hello.md"

  - name: "respond-to-greetings"
    type: "llm"
    prompt:
      file: "reply.gpt"
      inputs:
        greeting_markdown: "${greeting}"
    outputs: reply_block
    saveas:
      path: "${output_dir}/responses.md"
```

Highlights:

- The `variables` block declares `output_dir`, which is referenced later
  in the `saveas.path` fields using `${output_dir}`.
- The first step saves its LLM output into a pipeline variable called
  `greeting` and also writes that markdown to `output/hello.md`.
- The second step reads `${greeting}` and passes it into the `reply.gpt`
  prompt as `greeting_markdown`, then writes its result to
  `output/responses.md`.

## 3. Running the tutorial

From the project root (where `pipelines/` and `prompts/` live):

```bash
sp run --pipeline pipelines/hello-llmflow.yaml
```

On success, you should see two files:

- `output/hello.md` – the original multilingual greetings
- `output/responses.md` – replies to each greeting

Open them in your editor or viewer of choice and iterate on the prompts
as needed.

## 4. Next steps

- Change `language_count` in the first step to explore larger lists.
- Edit `prompts/hello.gpt` or `prompts/reply.gpt` to adjust tone,
  structure, or formatting.
- Add a third step that summarizes all replies into a short report and
  saves it to another file using `saveas`.
"""

LANGUAGE_QUICKREF_DOC = """# LLMFlow Language Quick Reference

This file is a compact, self-contained reference to the LLMFlow
pipeline language for day-to-day work in this repository.

If you have access to the engine repo, the full specification lives
in `docs/llmflow-language.md` there, but this quickref is designed to
be enough to author and review pipelines on its own.

## 1. Pipeline structure

```yaml
name: my_pipeline
description: |
  One-line or multi-line description of what this flow does.

variables:
  output_dir: "output"

llm_config:
  model: gpt-4o-mini
  max_tokens: 1024
  temperature: 0.2

linter_config:
  enabled: true
  treat_warnings_as_errors: true

steps:
  - name: first-step
    type: llm | function | for-each | save
    # ...
```

Key sections:

- `name`, `description`: human-readable name and summary for the flow.
- `variables`: global variables available to all steps.
- `llm_config`: default model parameters for `llm` steps.
- `linter_config`: controls validation behavior for this pipeline.
- `steps`: ordered list of operations that make up the flow.

## 2. Referencing variables and templates

In pipeline YAML, use `${var}` syntax to reference variables and
step outputs:

- `${output_dir}` – root-level variable.
- `${greeting}` – value produced by a previous step.
- `${scene.WLC}` – field access on an object.
- `${scene_list[0]}` – first element of a list.
- `${scene_list[*].Title}` – extract one field from every item; returns a flat list.

In prompt and template files (`*.gpt`, `*.md`), use `{{var}}`:

- `{{language_count}}`
- `{{greeting_markdown}}`
- `{{scene.WLC}}`

Prompt files usually include a small contract (often in a comment
block) that documents which inputs they expect ("requires" / "optional").
Make sure every required value is provided by the pipeline step
via `prompt.inputs`.

## 3. Common step types

### type: `llm`

Runs a prompt through an LLM and stores the response.

```yaml
- name: generate_text
  type: llm
  prompt:
    file: "template.gpt"
    inputs:
      topic: "${topic}"
  outputs: draft
  saveas:
    path: "${output_dir}/draft.md"
```

- `prompt.file` points to a prompt in `prompts/`.
- `prompt.inputs` provides values that the prompt template expects.
- `outputs` names the variable that will hold the LLM response.
- `saveas.path` writes that response to disk.

Optional extras you may see:

- `output_type: json` – ask the engine to parse the response as JSON.
- `log: debug` – per-step log level.

### type: `function`

Calls a Python function as part of the flow.

```yaml
- name: parse_data
  type: function
  function: some.module:callable
  inputs:
    raw: "${raw_text}"
  outputs: parsed
  saveas:
    path: "${output_dir}/parsed.json"
```

Use `function` steps for deterministic utilities: parsing, loading
files, rendering templates, reshaping JSON, etc.

### type: `for-each`

Loops over a list variable and runs nested steps for each item.

```yaml
- name: process_each_item
  type: for-each
  input: "${items}"
  item_var: item
  steps:
    - name: handle-item
      type: llm
      prompt:
        file: "item.gpt"
        inputs:
          item_text: "${item}"
      outputs: item_result
      append_to: all_results
```

- `input` points to a list value.
- `item_var` is the name used to refer to each element.
- Use `append_to` in nested steps to build a list across iterations.

### type: `save`

Writes literal content to disk without calling an LLM.

```yaml
- name: write-confirmation
  type: save
  content: |
    ✅ LLMFlow is installed and running.
    2 + 2 = ${total}
  saveas:
    path: "${output_dir}/hello-llmflow.txt"
```

Use `save` when you just need to materialize a small message or
artifact from existing variables.

### type: `if`

Conditionally executes a block of steps.

```yaml
- name: add-detail
  type: if
  condition: "${include_detail}"
  steps:
    - name: generate-detail
      type: llm
      prompt:
        file: "detail.gpt"
        inputs:
          topic: "${topic}"
      outputs: detail_text
```

- `condition` is evaluated first; if falsy the whole block is skipped.
- Any step type is valid in the nested `steps:` list.

### Step-level `condition:` (skip guard)

Any step (any type) can be skipped individually:

```yaml
- name: optional-step
  type: llm
  condition: "${run_optional}"
  prompt:
    file: "optional.gpt"
    inputs:
      data: "${data}"
  outputs: optional_result
```

The expression follows the same rules as `type: if` — variable reference,
Python eval expression, or boolean literal.

## 4. Saving outputs with `saveas`

Any step can write its primary output (or literal content) to a file:

```yaml
- name: save_report
  type: llm
  prompt:
    file: "report.gpt"
    inputs:
      data: "${analysis}"
  outputs: report_md
  saveas:
    path: "${output_dir}/report.md"
```

Notes:

- Parent directories are created automatically.
- You can include `${variables}` and nested fields inside the path.
- If you need multiple files, add more steps, each with its own
  `saveas`.

## 5. Running and linting pipelines

From the project root (where `pipelines/` lives):

```bash
sp run --pipeline pipelines/my-pipeline.yaml
```

To pass variables from the CLI:

```bash
sp run --pipeline pipelines/my-pipeline.yaml \
  --var passage="Psalm 23" \
  --var output_dir="output"
```

To validate a pipeline without running it:

```bash
sp lint pipelines/my-pipeline.yaml
```

The `linter_config` block in the pipeline controls how strict
validation should be (for example, whether warnings become errors).

## 6. Prompt file format (`.gpt`)

Every `.gpt` file must begin with a YAML frontmatter block that declares
the variables it expects. The linter enforces this contract.

```
---
requires:
  - language_count
optional: []
format: Markdown
description: Brief description of what this prompt does.
---
system: |
  You are a helpful assistant.
user: |
  Do something with {{language_count}} items.
```

Key rules:

- `requires:` — list of variable names the caller *must* provide via `prompt.inputs`.
- `optional:` — list of variable names the caller *may* provide.
- Variables in the body use `{{double_braces}}`.
- If `requires:` is missing, the linter cannot validate the contract and will
  emit warnings about undeclared inputs.
"""


GENERATED_MARKER = "<!-- Generated by sp init -->"


def _is_generated(path: Path) -> bool:
    """Return True if the file was created by sp init (has the generated marker)."""
    try:
        first_line = path.read_text(encoding="utf-8").split("\n", 1)[0].strip()
        return first_line == GENERATED_MARKER
    except OSError:
        return False


AI_OVERVIEW_DOC = """<!-- Generated by sp init -->
# LLMFlow — Repo Overview for AI Assistants

This repository contains LLMFlow pipelines, prompts, and outputs.
It was initialized with the `sp init` command.

## Layout

- `pipelines/` – YAML pipeline definitions
- `prompts/` – prompt templates used by `llm` steps
- `output/` – generated artifacts written by `saveas`
- `docs/` – human- and AI-facing documentation
  - `docs/tutorial.md` – walkthrough of the starter pipeline
  - `docs/llmflow-language-quickref.md` – compact language reference

## How AI helpers should use this repo

- Prefer reading `pipelines/` and `prompts/` directly when editing
  flows.
- Use `docs/tutorial.md` to understand the starter example and how
  variables + `saveas` work.
- Use `docs/llmflow-language-quickref.md` for common YAML keys and
  step types; defer to the upstream engine docs for advanced features.
"""

AI_RULES_DOC = """<!-- Generated by sp init -->
# AI Assistant Rules for This Repo

These guardrails apply to any language model collaborating on this
LLMFlow-based project.

1. **Respect the LLMFlow schema.** Only use documented keys like
   `name`, `type`, `prompt`, `inputs`, `outputs`, `llm_config`,
   `saveas`, and `append_to`. Do not invent new fields.
2. **Keep prompts and pipelines in sync.** If a prompt template expects
   a variable (e.g., `{{greeting_markdown}}`), ensure the corresponding
   pipeline step passes it via `prompt.inputs`.
3. **Preserve human review.** Generated files under `output/` are
   drafts. Do not assume they are final; humans review and edit them
   before publication.
4. **Be explicit about paths.** When suggesting changes, reference
   concrete files such as `pipelines/hello-llmflow.yaml` or
   `prompts/hello.gpt` so humans can verify easily.
5. **Avoid destructive changes.** Prefer additive edits (new steps,
   new pipelines) over deleting existing ones unless explicitly
   requested.
6. **Stay within documented capabilities.** Model- or provider-specific
   features (such as JSON response modes) should be used only when the
   upstream LLMFlow docs indicate support.
7. **Declare prompt contracts.** Every `.gpt` file must have a YAML
   frontmatter block at the top with a `requires:` list naming every
   variable the prompt body uses. Missing `requires:` means the linter
   cannot validate the pipeline and silent failures will occur:
   ```
   ---
   requires:
     - my_variable
   optional: []
   ---
   ```
8. **Use `project/TODO.md` as a session cache.** This file is the
   single source of truth for what is in flight right now. Read it
   at the start of every session before doing anything else.
   - **Active** — what is being worked on this session
   - **Backlog** — upcoming work, roughly prioritized; link GitHub
     Issues with `→ #N` so the permanent record is one hop away
   - **Done** — recently completed items (keep for context)
   - Fetch a GitHub Issue (`gh issue view N`) only when more detail
     is needed than the TODO link provides. Do not duplicate issue
     content in this file — just link and summarise.
9. **Draft GitHub Issues for human approval.** When something
   warrants a permanent record (a bug, a design decision, a feature
   request), draft the title and body and show it to the human.
   Only run `gh issue create --body-file f.md` after explicit
   approval. Never create issues silently.
"""

AI_INDEX_DOC = """<!-- Generated by sp init -->
# Document Index for AI Assistants

Use this index to decide which reference to consult when reasoning
about this repository.

| Topic | Go To | Notes |
| --- | --- | --- |
| **Active work / backlog** | ../../project/TODO.md | Read this first every session. Contains what is in progress and links to GitHub Issues. |
| Tutorial pipeline | ../tutorial.md | Step-by-step walkthrough of variables and `saveas`. |
| Language quick reference | ../llmflow-language-quickref.md | Core YAML structure, step types, and variable syntax. |
| Engine language spec (canonical) | https://github.com/nida-institute/LLMFlow/blob/main/docs/llmflow-language.md | Full specification maintained in the engine repo. |
| Engine tutorial (canonical) | https://github.com/nida-institute/LLMFlow/blob/main/docs/tutorial.md | Reference tutorial for the core project. |
"""

COPILOT_INSTRUCTIONS_DOC = """<!-- Generated by sp init -->
# Copilot Instructions for This LLMFlow Project

## Session Start

Read these first every session:
1. `project/TODO.md` — active work, blocked items, what NOT to touch
2. `docs/ai-context/index.md` — full AI context for this project

## Repository Context

This is an LLMFlow consumer project. It does NOT contain the LLMFlow engine source.
- Pipelines live in `pipelines/`
- Prompts live in `prompts/`
- Generated outputs live in `output/`
- The LLMFlow engine is installed separately: https://github.com/nida-institute/LLMFlow

## Workflow

**Always explain before implementing** — describe what files you will change and why before making changes.

**For pipeline changes:**
- Lint first: `sp lint --pipeline pipelines/<name>.yaml`
- Dry run: `sp run --pipeline pipelines/<name>.yaml --dry-run`
- All prompts must have `requires:` contracts in their frontmatter

**For significant changes (>2 files):**
1. Describe the diff and impact
2. Wait for approval before executing

**GitHub Issues:**
- Draft issue bodies in a temp file, then: `gh issue create --body-file /tmp/issue.md`
- Link from `project/TODO.md` with `→ #N`

## Transparency

When these instructions influence a decision, say so explicitly.
"""

VSCODE_DOC = """<!-- Generated by sp init -->
# VS Code Setup for LLMFlow Projects

Recommended settings and the privacy/convenience trade-offs for AI-assisted pipeline work.

## Recommended settings.json

Copy the block below into `.vscode/settings.json` (create the file if it doesn't exist).
Adjust to taste — the comments explain each section.

```json
{
  "files.trimTrailingWhitespace": true,
  "editor.largeFileOptimizations": false,

  // Prevent VS Code from offering to open parent folders as a workspace,
  // which can confuse Copilot about which repo it is in.
  "git.openRepositoryInParentFolders": "never",

  // Stack chat sessions vertically so long conversations are easier to scroll.
  "chat.viewSessions.orientation": "stacked",

  // --- Terminal auto-approve ---
  // Controls which commands Copilot can run in the terminal WITHOUT prompting.
  // Read the privacy section below before enabling anything beyond the defaults.
  "chat.tools.terminal.autoApprove": {

    // Safe read-only commands — approve freely.
    "pwd": true, "ls": true, "dir": true, "echo": true,
    "cat": true, "head": true, "tail": true, "wc": true,
    "nl": true, "grep": true, "rg": true, "find": true,
    "sort": true, "column": true, "date": true,
    "basename": true, "dirname": true, "which": true,
    "file": true, "stat": true,

    // Read-only git commands — approve.
    "/^git\\\\s+status\\\\b/": true,
    "/^git\\\\s+log\\\\b/": true,
    "/^git\\\\s+show\\\\b/": true,
    "/^git\\\\s+diff\\\\b/": true,
    "/^git\\\\s+ls-files\\\\b/": true,
    "/^git\\\\s+grep\\\\b/": true,
    "/^git\\\\s+branch\\\\b$/": true,

    // Commands that change state — keep at false (require confirmation).
    "rm": false, "rmdir": false, "del": false,
    "curl": false, "wget": false,
    "chmod": false, "chown": false,
    "kill": false, "ps": false,

    // Scripting / eval — always false.
    "xargs": false, "eval": false, "jq": false
  }
}
```

## Privacy vs. convenience

`chat.tools.terminal.autoApprove` is a direct trade-off:

**More approvals = less friction, more exposure.**

| Risk | What it means |
|---|---|
| **Read commands are safe** | `ls`, `cat`, `grep` etc. only read from your disk. Approving them just saves a click. |
| **Write/delete commands are not** | `rm`, `del` can destroy work. Always require confirmation. |
| **Network commands are not** | `curl`, `wget`, `Invoke-WebRequest` can exfiltrate data or download malicious payloads. Always require confirmation. |
| **`eval` / `Invoke-Expression` are never safe** | These can run arbitrary generated code without any further prompt. Never approve. |
| **`cd` is subtle** | Changing directory mid-session can cause Copilot to operate in the wrong scope. Leave at false. |

**The recommended config above approves only read-only commands.** This eliminates most confirmation dialogs during normal pipeline development (reading files, checking git status) while keeping every state-changing operation behind a prompt.

If you are working on a project with sensitive content (Bible translations, proprietary data), be aware that even read-only auto-approval means Copilot can scan any file in the workspace and include it in its context window. That is intentional for pipeline development but worth understanding.
"""

PROJECT_TODO = """# Project TODO

## 🔥 Active
- [ ]

## 📋 Backlog

### 🎓 Tutorial: get started with AI + GitHub issues

- [ ] Run the hello pipeline: `sp run --pipeline pipelines/hello.yaml`
- [ ] Explore the pipeline: open `pipelines/hello.yaml` in VS Code and use Copilot `/explain` on the file contents
- [ ] Explore the prompts: open each file in `prompts/` and use `/explain` to understand the frontmatter contract and prompt template
- [ ] Brainstorm extensions: ask GitHub Copilot "What are some interesting ways I could modify or extend this pipeline?"
- [ ] Extend the pipeline: implement one new idea with AI assistance — new step, new prompt, or modified variable
- [ ] Debug a run: introduce an error, run the pipeline, paste the terminal output into Copilot and ask it to diagnose and fix
- [ ] Triage: review open GitHub issues on this repo and close any that have been addressed
- [ ] Plan next steps: ask Copilot "Look at the open issues and what we have done so far. What should we work on next?"

## ✅ Done

---
_Audit notes and QA reports → project/audits/_
_Pipeline decisions → project/decisions.md (create when needed)_
"""

PROJECT_AUDITS_README = """<!-- Generated by sp init -->
# Audits

Store pipeline QA reports, output review notes, and lint snapshots here.

## Suggested naming

```
YYYY-MM-DD_<passage-or-scope>_<pipeline-or-step>.md
```

Examples:
- `2026-03-17_Ruth-1_storyflow-psalms.md`
- `2026-03-18_full-run_semlex-multipass.md`

## What belongs here

- Manual review of LLM outputs (correctness, tone, coverage)
- Notes on specific failures and how they were resolved
- Before/after comparisons when a prompt or pipeline changes
- Coverage validator reports

## What does not belong here

- Pipeline YAML files → `pipelines/`
- Generated artifacts → `output/`
- Active tasks → `project/TODO.md`
"""


def init_project(base_dir: Path, update: bool = False) -> None:
    """Initialize a new LLMFlow project structure.

    When update=True, regenerate any file that carries the
    '<!-- Generated by sp init -->' marker, leaving hand-edited
    files untouched.
    """
    prompts_dir = base_dir / "prompts"
    pipelines_dir = base_dir / "pipelines"
    output_dir = base_dir / "output"
    docs_dir = base_dir / "docs"
    ai_context_dir = docs_dir / "ai-context"
    project_dir = base_dir / "project"
    audits_dir = project_dir / "audits"
    vscode_dir = base_dir / ".vscode"
    github_dir = base_dir / ".github"

    prompts_dir.mkdir(parents=True, exist_ok=True)
    pipelines_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)
    ai_context_dir.mkdir(parents=True, exist_ok=True)
    project_dir.mkdir(parents=True, exist_ok=True)
    audits_dir.mkdir(parents=True, exist_ok=True)
    vscode_dir.mkdir(parents=True, exist_ok=True)
    github_dir.mkdir(parents=True, exist_ok=True)

    prompt_path = prompts_dir / "hello.gpt"
    reply_prompt_path = prompts_dir / "reply.gpt"
    pipeline_path = pipelines_dir / "hello-llmflow.yaml"
    hello_yaml_path = pipelines_dir / "hello.yaml"
    tutorial_doc_path = docs_dir / "tutorial.md"
    language_quickref_path = docs_dir / "llmflow-language-quickref.md"
    vscode_doc_path = docs_dir / "vscode.md"
    ai_overview_path = ai_context_dir / "overview.md"
    ai_rules_path = ai_context_dir / "rules.md"
    ai_index_path = ai_context_dir / "index.md"
    project_todo_path = project_dir / "TODO.md"
    project_audits_readme_path = audits_dir / "README.md"
    copilot_instructions_path = github_dir / "copilot-instructions.md"

    if not prompt_path.exists():
        prompt_path.write_text(HELLO_PROMPT, encoding="utf-8")
        logger.info("Created prompts/hello.gpt")
    elif update and _is_generated(prompt_path):
        prompt_path.write_text(HELLO_PROMPT, encoding="utf-8")
        logger.info("Updated prompts/hello.gpt")
    else:
        logger.info("prompts/hello.gpt already exists; leaving as-is.")

    if not reply_prompt_path.exists():
      reply_prompt_path.write_text(HELLO_REPLY_PROMPT, encoding="utf-8")
      logger.info("Created prompts/reply.gpt")
    elif update and _is_generated(reply_prompt_path):
      reply_prompt_path.write_text(HELLO_REPLY_PROMPT, encoding="utf-8")
      logger.info("Updated prompts/reply.gpt")
    else:
      logger.info("prompts/reply.gpt already exists; leaving as-is.")

    if not pipeline_path.exists():
        pipeline_path.write_text(HELLO_PIPELINE, encoding="utf-8")
        logger.info("Created pipelines/hello-llmflow.yaml")
    elif update and _is_generated(pipeline_path):
        pipeline_path.write_text(HELLO_PIPELINE, encoding="utf-8")
        logger.info("Updated pipelines/hello-llmflow.yaml")
    else:
        logger.info("pipelines/hello-llmflow.yaml already exists; leaving as-is.")

    if not hello_yaml_path.exists():
        hello_yaml_path.write_text(HELLO_YAML, encoding="utf-8")
        logger.info("Created pipelines/hello.yaml")
    elif update and _is_generated(hello_yaml_path):
        hello_yaml_path.write_text(HELLO_YAML, encoding="utf-8")
        logger.info("Updated pipelines/hello.yaml")
    else:
        logger.info("pipelines/hello.yaml already exists; leaving as-is.")

    if not tutorial_doc_path.exists():
        tutorial_doc_path.write_text(TUTORIAL_DOC, encoding="utf-8")
        logger.info("Created docs/tutorial.md")
    elif update and _is_generated(tutorial_doc_path):
        tutorial_doc_path.write_text(TUTORIAL_DOC, encoding="utf-8")
        logger.info("Updated docs/tutorial.md")
    else:
        logger.info("docs/tutorial.md already exists; leaving as-is.")

    if not language_quickref_path.exists():
        language_quickref_path.write_text(LANGUAGE_QUICKREF_DOC, encoding="utf-8")
        logger.info("Created docs/llmflow-language-quickref.md")
    elif update and _is_generated(language_quickref_path):
        language_quickref_path.write_text(LANGUAGE_QUICKREF_DOC, encoding="utf-8")
        logger.info("Updated docs/llmflow-language-quickref.md")
    else:
        logger.info("docs/llmflow-language-quickref.md already exists; leaving as-is.")

    if not ai_overview_path.exists():
        ai_overview_path.write_text(AI_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/overview.md")
    elif update and _is_generated(ai_overview_path):
        ai_overview_path.write_text(AI_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/overview.md")
    else:
        logger.info("docs/ai-context/overview.md already exists; leaving as-is.")

    if not ai_rules_path.exists():
        ai_rules_path.write_text(AI_RULES_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/rules.md")
    elif update and _is_generated(ai_rules_path):
        ai_rules_path.write_text(AI_RULES_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/rules.md")
    else:
        logger.info("docs/ai-context/rules.md already exists; leaving as-is.")

    if not ai_index_path.exists():
        ai_index_path.write_text(AI_INDEX_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/index.md")
    elif update and _is_generated(ai_index_path):
        ai_index_path.write_text(AI_INDEX_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/index.md")
    else:
        logger.info("docs/ai-context/index.md already exists; leaving as-is.")

    if not vscode_doc_path.exists():
        vscode_doc_path.write_text(VSCODE_DOC, encoding="utf-8")
        logger.info("Created docs/vscode.md")
    elif update and _is_generated(vscode_doc_path):
        vscode_doc_path.write_text(VSCODE_DOC, encoding="utf-8")
        logger.info("Updated docs/vscode.md")
    else:
        logger.info("docs/vscode.md already exists; leaving as-is.")

    # project/TODO.md — never overwritten; hand-edited from first run
    if not project_todo_path.exists():
        project_todo_path.write_text(PROJECT_TODO, encoding="utf-8")
        logger.info("Created project/TODO.md")
    else:
        logger.info("project/TODO.md already exists; leaving as-is.")

    if not project_audits_readme_path.exists():
        project_audits_readme_path.write_text(PROJECT_AUDITS_README, encoding="utf-8")
        logger.info("Created project/audits/README.md")
    elif update and _is_generated(project_audits_readme_path):
        project_audits_readme_path.write_text(PROJECT_AUDITS_README, encoding="utf-8")
        logger.info("Updated project/audits/README.md")
    else:
        logger.info("project/audits/README.md already exists; leaving as-is.")

    if not copilot_instructions_path.exists():
        copilot_instructions_path.write_text(COPILOT_INSTRUCTIONS_DOC, encoding="utf-8")
        logger.info("Created .github/copilot-instructions.md")
    elif update and _is_generated(copilot_instructions_path):
        copilot_instructions_path.write_text(COPILOT_INSTRUCTIONS_DOC, encoding="utf-8")
        logger.info("Updated .github/copilot-instructions.md")
    else:
        logger.info(".github/copilot-instructions.md already exists; leaving as-is.")

    logger.info("Output directory ready at ./output")


def list_pipelines(directory: str) -> list[str]:
    """List all YAML pipeline files in a directory."""
    base = Path(directory)
    if not base.exists():
        return []
    pipelines: list[str] = []
    for pattern in ("*.yaml", "*.yml"):
        for path in base.rglob(pattern):
            if path.is_file():
                pipelines.append(str(path.relative_to(base)))
    return sorted(dict.fromkeys(pipelines))