"""CLI utility functions for Scripture Pipelines project initialization."""
import logging
import os
import re
import stat
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

import click

logger = logging.getLogger(__name__)

HELLO_PROMPT = """---
requires:
  - language_count
optional: []
format: Markdown
description: Generate a multilingual greeting list for {language_count} languages.
---
system: |
  You are a friendly assistant who showcases multilingual greetings.
user: |
  Pick {{language_count}} languages randomly.
  For each one, identify the language in English, share a native-script greeting, and add a short cultural note.
  Respond as a markdown bullet list.
"""

HELLO_REPLY_PROMPT = """---
requires:
  - greeting_markdown
optional: []
format: Markdown
description: Reply to the {greeting_markdown} bullet list with cultural notes.
---
system: |
  You are a cultural etiquette coach who replies warmly to multilingual greetings.
user: |
  You received this markdown list of greetings:

  {{greeting_markdown}}

  For each bullet, craft a short reply in the same language (when appropriate) plus an English explanation of the cultural nuance you appreciated. Return markdown with the same bullet structure.
"""

HELLO_PIPELINE = """name: "Hello Multilingual Pipeline"
description: |
  Sample pipeline generated by `sp init`.
  Run it with:
    sp run --pipeline pipelines/hello-llmflow.yaml
variables:
  prompts_dir: "prompts"
  output_dir: "outputs"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 500

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    output: greeting
    saveas:
      path: "${output_dir}/hello.md"

  - name: "respond-to-greetings"
    type: "llm"
    prompt:
      file: "reply.gpt"
      inputs:
        greeting_markdown: "${greeting}"
    output: reply_block
    saveas:
      path: "${output_dir}/responses.md"
"""

HELLO_YAML = """name: "Hello Scripture Pipelines"
description: |
  Minimal starter pipeline for Scripture Pipelines.
  Run with: sp run --pipeline pipelines/hello.yaml
variables:
  output_dir: "outputs"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 500

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    output: greeting
    saveas:
      path: "${output_dir}/greeting.md"
"""

TUTORIAL_DOC = """# Scripture Pipelines Project Tutorial

This repository was initialized with `sp init`.
It includes a minimal, working example that shows how to declare variables,
pass them between steps, and write results to files using `saveas`.

## 1. Project layout

After running `sp init` in an empty directory, you should see:

```
./
├── outputs/
├── pipelines/
│   └── hello-llmflow.yaml
└── prompts/
    ├── hello.gpt
    └── reply.gpt
```

Pipelines live under `pipelines/`, prompt templates live under `prompts/`,
and generated content is written into `outputs/`.

## 2. Tutorial pipeline

The tutorial pipeline is defined in `pipelines/hello-llmflow.yaml`:

```yaml
name: "Hello Multilingual Pipeline"
variables:
  prompts_dir: "prompts"
  output_dir: "outputs"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.2

steps:
  - name: "multilingual-greeting"
    type: "llm"
    prompt:
      file: "hello.gpt"
      inputs:
        language_count: 5
    output: greeting
    saveas:
      path: "${output_dir}/hello.md"

  - name: "respond-to-greetings"
    type: "llm"
    prompt:
      file: "reply.gpt"
      inputs:
        greeting_markdown: "${greeting}"
    output: reply_block
    saveas:
      path: "${output_dir}/responses.md"
```

Highlights:

- The `variables` block declares `output_dir`, which is referenced later
  in the `saveas.path` fields using `${output_dir}`.
- The first step saves its LLM output into a pipeline variable called
  `greeting` and also writes that markdown to `outputs/hello.md`.
- The second step reads `${greeting}` and passes it into the `reply.gpt`
  prompt as `greeting_markdown`, then writes its result to
  `outputs/responses.md`.

## 3. Running the tutorial

From the project root (where `pipelines/` and `prompts/` live):

```bash
sp run --pipeline pipelines/hello-llmflow.yaml
```

On success, you should see two files:

- `outputs/hello.md` – the original multilingual greetings
- `outputs/responses.md` – replies to each greeting

Open them in your editor or viewer of choice and iterate on the prompts
as needed.

## 4. Next steps

- Change `language_count` in the first step to explore larger lists.
- Edit `prompts/hello.gpt` or `prompts/reply.gpt` to adjust tone,
  structure, or formatting.
- Add a third step that summarizes all replies into a short report and
  saves it to another file using `saveas`.
"""

LANGUAGE_QUICKREF_DOC = """# Scripture Pipelines Language Quick Reference

This file is a compact, self-contained reference to the Scripture Pipelines
pipeline language for day-to-day work in this repository.

If you have access to the engine repo, the full specification lives
in `docs/llmflow-language.md` there, but this quickref is designed to
be enough to author and review pipelines on its own.

## 1. Pipeline structure

```yaml
name: my_pipeline
description: |
  One-line or multi-line description of what this flow does.

variables:
  output_dir: "outputs"

llm_config:
  model: gpt-4o-mini
  max_tokens: 1024
  temperature: 0.2

linter_config:
  enabled: true
  treat_warnings_as_errors: true

steps:
  - name: first-step
    type: llm | function | for-each | window | save | if
    # ...
```

Key sections:

- `name`, `description`: human-readable name and summary for the flow.
- `variables`: global variables available to all steps.
- `llm_config`: default model parameters for `llm` steps.
- `linter_config`: controls validation behavior for this pipeline.
- `steps`: ordered list of operations that make up the flow.

## 2. Referencing variables and templates

In pipeline YAML, use `${var}` syntax to reference variables and
step outputs:

- `${output_dir}` – root-level variable.
- `${greeting}` – value produced by a previous step.
- `${scene.WLC}` – field access on an object.
- `${scene_list[0]}` – first element of a list.
- `${scene_list[-1]}` – last element of a list.
- `${scene_list[-1].field}` – field on the last element.
- `${scene_list[0].field}` – field on the first element.
- `${scene_list[:-1]}` – every element except the last.
- `${scene_list[-10:]}` – last 10 elements (returns all if fewer than 10).
- `${scene_list[*].Title}` – extract one field from every item; returns a flat list.
- `${scene_list[-3:][*].Title}` – field from each of the last 3 items.

In prompt and template files (`*.gpt`, `*.md`), use `{{var}}`:

- `{{language_count}}`
- `{{greeting_markdown}}`
- `{{scene.WLC}}`

Prompt files usually include a small contract (often in a comment
block) that documents which inputs they expect ("requires" / "optional").
Make sure every required value is provided by the pipeline step
via `prompt.inputs`.

## 3. Common step types

### type: `llm`

Runs a prompt through an LLM and stores the response.

```yaml
- name: generate_text
  type: llm
  prompt:
    file: "template.gpt"
    inputs:
      topic: "${topic}"
  output: draft
  saveas:
    path: "${output_dir}/draft.md"
```

- `prompt.file` points to a prompt in `prompts/`.
- `prompt.inputs` provides values that the prompt template expects.
- `outputs` names the variable that will hold the LLM response.
- `saveas.path` writes that response to disk.

Optional extras you may see:

- `output_type: json` – ask the engine to parse the response as JSON.
- `log: debug` – per-step log level.

### type: `function`

Calls a Python function as part of the flow.

```yaml
- name: parse_data
  type: function
  function: some.module:callable
  inputs:
    raw: "${raw_text}"
  output: parsed
  saveas:
    path: "${output_dir}/parsed.json"
```

Use `function` steps for deterministic utilities: parsing, loading
files, rendering templates, reshaping JSON, etc.

### type: `for-each`

Loops over a list variable and runs nested steps for each item.

```yaml
- name: process_each_item
  type: for-each
  for: item
  in: "${items}"
  parallel: 4                      # optional: run up to 4 iterations concurrently
  group_by: "${item.category}"     # optional: group results by this field
  order_by: "${item.sequence}"     # optional: sort results within groups
  steps:
    - name: handle-item
      type: llm
      prompt:
        file: "item.gpt"
        inputs:
          item_text: "${item}"
      output: item_result
      append_to: all_results
```

- `for` is the name used to refer to each element (XQuery-style: `for $x in $list`).
- `in` points to the list value.
- Use `append_to` in nested steps to build a list across iterations.
- `parallel: N` runs N iterations concurrently; results are collected in
  input order regardless. Omit for sequential execution (default).
- `group_by` and `order_by` accept `${expr}` expressions evaluated against
  each item. `group_by` groups `append_to` results by the expression value;
  `order_by` sorts within each group.

### type: `window`

Slides over a list in overlapping or tumbling windows, running nested
steps on each slice. Useful when a list is too large to process at once.

```yaml
- name: segment_by_windows
  type: window
  for: window_content
  in: "${content_list}"
  size: 50                   # fixed: 50 items per window
  # or: size_by_tokens: 4000 # token-aware: ~4000 tokens per window
  include_partial: true      # include the last partial window
  steps:
    - name: process_window
      type: llm
      prompt:
        file: "process.gpt"
        inputs:
          chunk: "${window_content}"
      output: window_result
      append_to: all_results

    # Optional: dynamic cursor — tell the engine where the next window starts.
    # Without this, windows advance by the full size (tumbling / non-overlapping).
    #
    # Two halves, and half is worse than none:
    #   1. DISCARD the last logical unit of a non-final window. The physical cut may
    #      have truncated it, so its end is not known. The next window re-decides it.
    #   2. RESUME from the trailing edge of the last unit you KEPT — never from the
    #      opening of the unit you dropped. If the model left a gap between them, a
    #      cursor set to the dropped unit's opening skips it and nothing sees it again.
    # The final window keeps everything: nothing truncated it.
    - !window_advance
      name: advance_cursor
      cursor: next_start      # a LIST INDEX into `in:` — not a domain identifier
      step:
        name: compute_next
        type: function
        function: plugins.windowing.content_index_of_sid
        inputs:
          # [-2] is the last unit kept, because [-1] was discarded as possibly cut.
          # Its trailing edge, not its opening.
          verse_sid: "${window_result.pericopes[-2].first_verse_sid_after_pericope}"
          content: "${content_list}"
          # A domain boundary has to be converted to a position; that is all this
          # function does.
        output: next_start
```

- `size` — fixed item count per window. Required even in cursor mode, where it bounds
  how far each window may reach.
- `size_by_tokens` — token-aware; requires `model` key (inherits from `llm_config`).
- `include_partial: true` — process the final window even if it is shorter than `size`.
- `!window_advance` — when present, switches to dynamic (cursor-driven) mode.
  The inner `step` runs each iteration; if its `cursor` variable is `null`
  the loop stops after the current window.
- Two guards, both raising rather than misbehaving: a cursor that is not a non-negative
  integer is rejected, and a cursor that does not advance beyond the current start raises
  instead of looping forever.
- Use `size`/`stride` when list items are independent (summarise every 10 reviews); use a
  cursor whenever the LLM is finding structure *inside* the block. See "Physical windows,
  logical units" in the Scripture Pipelines language reference for why.

### Cross-iteration state in `for-each` and `window`

Each iteration starts from a **fresh copy of the outer context**. Variables set
inside an iteration are not automatically visible to the next one — unless they
are propagated out via `outputs` or `append_to`.

**`outputs` (last-iteration-wins):** the final value written by each iteration
replaces the outer variable. Each subsequent iteration sees the updated value.

**`append_to` (accumulating list):** each iteration appends to a list in the
outer context. Subsequent iterations see the growing list — including the items
appended by earlier iterations. This enables "rolling context" patterns:

```yaml
- name: analyze_pericopes
  type: for-each
  for: pericope
  in: "${leaf_pericopes}"
  steps:
    - name: analyze
      type: llm
      prompt:
        file: analyze.gpt
        inputs:
          passage: "${pericope.canonical_reference}"
          # Only pass the last 10 summaries — prior_pericopes grows each iteration
          prior_context: "${prior_pericopes[-10:]}"
      output: pericope_analysis

    - name: summarize
      type: function
      function: llmflow.utils.data.pick_fields
      inputs:
        obj: "${pericope_analysis}"
        fields: ["title", "themes"]
      output: summary
      append_to: prior_pericopes   # visible to next iteration
```

The slice `${prior_pericopes[-10:]}` always returns the last 10 items,
or all items if fewer than 10 have accumulated so far.

### type: `save`

Writes literal content to disk without calling an LLM.

```yaml
- name: write-confirmation
  type: save
  content: |
    ✅ Scripture Pipelines is installed and running.
    2 + 2 = ${total}
  saveas:
    path: "${output_dir}/hello-llmflow.txt"
```

Use `save` when you just need to materialize a small message or
artifact from existing variables.

### type: `if`

Conditionally executes a block of steps.

```yaml
- name: add-detail
  type: if
  condition: "${include_detail}"
  steps:
    - name: generate-detail
      type: llm
      prompt:
        file: "detail.gpt"
        inputs:
          topic: "${topic}"
      output: detail_text
```

- `condition` is evaluated first; if falsy the whole block is skipped.
- Any step type is valid in the nested `steps:` list.

### Step-level `condition:` (skip guard)

Any step (any type) can be skipped individually:

```yaml
- name: optional-step
  type: llm
  condition: "${run_optional}"
  prompt:
    file: "optional.gpt"
    inputs:
      data: "${data}"
  output: optional_result
```

The expression follows the same rules as `type: if` — variable reference,
Python eval expression, or boolean literal.

## 4. Saving outputs with `saveas`

Any step can write its primary output (or literal content) to a file:

```yaml
- name: save_report
  type: llm
  prompt:
    file: "report.gpt"
    inputs:
      data: "${analysis}"
  output: report_md
  saveas:
    path: "${output_dir}/report.md"
```

Notes:

- Parent directories are created automatically.
- You can include `${variables}` and nested fields inside the path.
- If you need multiple files, add more steps, each with its own
  `saveas`.

## 5. Running and linting pipelines

From the project root (where `pipelines/` lives):

```bash
sp run --pipeline pipelines/my-pipeline.yaml
```

To pass variables from the CLI:

```bash
sp run --pipeline pipelines/my-pipeline.yaml \
  --var passage="Psalm 23" \
  --var output_dir="outputs"
```

To validate a pipeline without running it:

```bash
sp lint pipelines/my-pipeline.yaml
```

The `linter_config` block in the pipeline controls how strict
validation should be (for example, whether warnings become errors).

## 6. Prompt file format (`.gpt`)

Every `.gpt` file must begin with a YAML frontmatter block that declares
the variables it expects. The linter enforces this contract.

```
---
requires:
  - language_count
optional: []
format: Markdown
description: Brief description of what this prompt does.
---
system: |
  You are a helpful assistant.
user: |
  Do something with {{language_count}} items.
```

Key rules:

- `requires:` — list of variable names the caller *must* provide via `prompt.inputs`.
- `optional:` — list of variable names the caller *may* provide.
- Variables in the body use `{{double_braces}}`.
- If `requires:` is missing, the linter cannot validate the contract and will
  emit warnings about undeclared inputs.
"""


GENERATED_MARKER = "<!-- Generated by sp init -->"


def _is_generated(path: Path) -> bool:
    """Return True if the file was created by sp init (has the generated marker)."""
    try:
        first_line = path.read_text(encoding="utf-8").split("\n", 1)[0].strip()
        return first_line == GENERATED_MARKER
    except OSError:
        return False


LLMFLOW_BLOCK_BEGIN = "<!-- BEGIN llmflow-init: {name} -->"
LLMFLOW_BLOCK_END = "<!-- END llmflow-init: {name} -->"


def read_delimited_block(path: Path, block_name: str) -> Optional[str]:
    """Return the content of a named llmflow-init block, or None if it is not there.

    The counterpart to `_upsert_delimited_block`. `sp doctor` needs it because sp owns
    its *block* in `.cursorrules` and `.windsurfrules`, not the whole file — comparing
    the file against the bare constant reports permanent divergence and would strip a
    project's own content along with the delimiters (#204, plan D10).
    """
    if not path.is_file():
        return None

    begin = LLMFLOW_BLOCK_BEGIN.format(name=block_name)
    end = LLMFLOW_BLOCK_END.format(name=block_name)
    match = re.search(
        re.escape(begin) + r"\n(.*?)\n" + re.escape(end),
        path.read_text(encoding="utf-8"),
        re.DOTALL,
    )
    return match.group(1) if match else None


def _upsert_delimited_block(path: Path, block_name: str, content: str) -> str:
    """Append or replace a named llmflow-init block in a file.

    If the file does not exist, creates it with just the block.
    If the file exists but has no matching block, appends the block.
    If the file exists and has a matching block, replaces only that block.

    Returns "created", "appended", or "updated".
    """
    begin = LLMFLOW_BLOCK_BEGIN.format(name=block_name)
    end = LLMFLOW_BLOCK_END.format(name=block_name)
    block = f"{begin}\n{content}\n{end}\n"

    if not path.exists():
        path.write_text(block, encoding="utf-8")
        return "created"

    existing = path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end) + r"\n?",
        re.DOTALL,
    )
    if pattern.search(existing):
        updated = pattern.sub(block, existing)
        path.write_text(updated, encoding="utf-8")
        return "updated"
    else:
        sep = "\n" if existing.endswith("\n") else "\n\n"
        path.write_text(existing + sep + block, encoding="utf-8")
        return "appended"


# ---------------------------------------------------------------------------
# AI assistant configuration content blocks
# ---------------------------------------------------------------------------

CLAUDE_MD_LLMFLOW_BLOCK = """\
## Scripture Pipelines Project

This project uses the Scripture Pipelines declarative pipeline engine (`sp` CLI).

### Communication protocol

Address the user as "Captain" or "Sir" — the Captain commands (sets direction),
the AI implements (executes and provides analysis).

### Session start

1. Read `docs/ai-context/project/index.md` — this project's own map, and yours to keep current.
   `docs/ai-context/sp/index.md` lists the documents Scripture Pipelines ships.
2. Check `project/TODO.md` — active work and what NOT to touch.
3. Load only context relevant to the current task.

### Repository layout

- `pipelines/` — YAML pipeline definitions
- `prompts/` — prompt templates (`.gpt` files) used by `llm` steps
- `outputs/` — generated artifacts written by `saveas`
- `docs/ai-context/project/` — yours: this project's map, description and rules (read `project/index.md` first)
- `docs/ai-context/sp/` — Scripture Pipelines' own documents, regenerated; do not hand-edit

### Workflow guidelines

- **Explain before implementing** — describe files you will change and why; wait for approval.
- **Test-driven** — write a failing test first for bugs and features.
- **Scope discipline** — do not improve code outside the requested scope.

### Shell commands

- **Never `cd /path && command`** — specify the path as an argument instead: `git -C /path`, `grep -r pattern /path/`, `find /path/`, `pytest /path/`. The `cd` form triggers approval prompts.
- **No piping bash commands** — use the Read, Edit, Write, and Grep tools instead. They never require approval.
- **Bash inline Python** — use `hatch run python << 'EOF'` heredoc; never `-c "..."` with multiline content.

### Pipeline CLI

```bash
sp run --pipeline pipelines/my-pipeline.yaml --var key=value
sp lint --pipeline pipelines/my-pipeline.yaml
sp run --pipeline pipelines/my-pipeline.yaml --dry-run
```

**Never run `sp run` without explicit direction from the Captain.** Running a pipeline
calls LLMs (incurring cost), writes output files to disk, and may take significant time.
These are not reversible actions the AI should take autonomously.

- Proposing a pipeline run or showing the command is fine.
- Explicit direction ("run it", "go ahead", or naming a specific pipeline and passage)
  is required before executing.
- Prior pipeline runs in this session do NOT authorize future runs. Each run requires
  its own explicit direction.

### AI authority boundaries

Do not declare output "production ready", "approved", or "suitable for use with groups".

- OK: "Technical compliance verified. Human review should assess appropriately."
- OK: "Generation completed. Quality assessment requires domain expert review."
- NOT OK: "Production ready" / "Approved" / "Suitable for immediate use"

### This file and its limits

**CLAUDE.md belongs to the Captain.** The AI may propose additions or changes in conversation — showing exact content — but must never write to this file without explicit approval.

**HARD PROHIBITION: Never modify anything under `docs/ai-context/sp/`.** Those are Scripture Pipelines' own documents; they are regenerated, so an edit there is lost and a fix belongs upstream. Everything under `docs/ai-context/project/` is the opposite — it is this project's, created once and never overwritten, and it is where anything you want to keep belongs.
The `sp/` documents are written by `sp init` and refreshed by `sp init --update` and `sp doctor`; the AI reports findings and proposes changes in conversation rather than editing them, because an edit there is overwritten on the next run and the fix belongs in the engine.

Everything under `project/` is yours: `index.md` for the map, `overview.md` for what this project is, `rules.md` for constraints that hold here and nowhere else, and `project.md` for facts, conventions and gotchas. `sp` creates each of them once and never touches them again, so write in them freely.

**HARD PROHIBITION: Never create or modify files in the project memory directory without explicit approval.**
Memory files belong to the Captain. Propose additions or deletions in conversation; never write them unilaterally.
"""

# A pointer, not a copy (#204, plan D4/A2).
#
# This block used to restate the project's rules in six lines, and `.windsurfrules` was
# assigned the same string. That summary omitted the `sp run` prohibition, the
# memory-file prohibition and the `docs/ai-context/` prohibition, all of which the
# Copilot document carried — so an agent reading `.cursorrules` as its rules found
# nothing saying that running a pipeline spends money and needs the Captain's say-so.
#
# Three lossy copies of one rule set is how that happens. A signpost cannot drift out of
# alignment with the rules because it carries none of them.
ASSISTANT_RULES_POINTER = """\
## Scripture Pipelines project rules

This project uses the Scripture Pipelines pipeline engine (`sp` CLI).

**The rules for this project are in `docs/ai-context/sp/rules.md`. Read it first — it is
authoritative.** Start from `docs/ai-context/project/index.md`, this project's own map;
`docs/ai-context/sp/index.md` lists what Scripture Pipelines ships.

Nothing is restated here. A summary would drift from the rules it summarises, and an
assistant acting on the summary would be acting on a weaker rule set than the one this
project actually enforces.
"""

CURSORRULES_LLMFLOW_BLOCK = ASSISTANT_RULES_POINTER

WINDSURFRULES_LLMFLOW_BLOCK = ASSISTANT_RULES_POINTER


def _install_claude_skills(base_dir: Path, sp_home: Optional[Path] = None) -> list[str]:
    """Copy skills from ~/.sp/skills/ into <repo>/.claude/skills/ (#204, plan D1-A′).

    Claude Code reads skills from exactly two places: `~/.claude/skills/` (personal) and
    `<repo>/.claude/skills/` (project). `~/.sp/skills/` is Scripture Pipelines's own directory and is
    invisible to it — a skill left there is not invocable and `/load-context` does not
    exist as a command. The copy is not redundancy; it is the only thing that makes the
    skill work.

    Captain's D1 ruling: *"I can live with a minimal use of .claude, I think it should be
    project level, and it should load all of our ~/.sp skills and any local project
    skills."* Nothing is written to `~/.claude` — a machine-scoped write is a permission
    only the machine's owner can grant, and this repo-scoped copy needs no such grant.

    The whole skill directory is copied, not just `SKILL.md`. The previous version copied
    one file, which was correct only for as long as every skill stayed single-file.

    Returns the names of the skills installed.
    """
    if sp_home is None:
        sp_home = Path.home() / ".sp"

    sp_skills_dir = sp_home / "skills"
    if not sp_skills_dir.is_dir():
        return []

    project_skills_dir = base_dir / ".claude" / "skills"
    installed: list[str] = []

    for skill_dir in sorted(sp_skills_dir.iterdir()):
        if not skill_dir.is_dir() or not (skill_dir / "SKILL.md").exists():
            continue

        target_dir = project_skills_dir / skill_dir.name
        for source in sorted(skill_dir.rglob("*")):
            if source.is_dir():
                continue
            target = target_dir / source.relative_to(skill_dir)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(source.read_bytes())
        installed.append(skill_dir.name)

    return installed


def _configure_copilot(base_dir: Path, update: bool) -> None:
    """Configure GitHub Copilot instructions via a delimited block.

    Block-managed like `.cursorrules` and `.windsurfrules`, and sharing their content
    (`ASSISTANT_RULES_POINTER`). Until 2026-08-24 this file alone was written whole, which is
    why `sp doctor` replaced 72 lines of a consumer repo's own Copilot instructions with the
    three-line pointer — the two sibling files kept theirs, because sp owns only its block
    there. Ruled Q2 of `project/plans/plan-init-doctor-unification.md`: *"give it
    `block: workflow` like the other two."*

    `update` is unused and kept for signature symmetry with the other `_configure_*`
    helpers: an upsert is idempotent, so there is nothing for a flag to select.
    """
    github_dir = base_dir / ".github"
    github_dir.mkdir(exist_ok=True)
    path = github_dir / "copilot-instructions.md"
    action = _upsert_delimited_block(path, "workflow", ASSISTANT_RULES_POINTER)
    click.echo(f"  {action.capitalize()} .github/copilot-instructions.md (llmflow-init block)")


def _configure_claude_code(base_dir: Path, update: bool) -> None:
    """Configure Claude Code: the CLAUDE.md block and the project's skills.

    Both writes land inside `base_dir`. Nothing is machine-scoped any more (D1-A′), so
    nothing here needs the user's consent — see `_configure_ai_assistants`.
    """
    claude_md = base_dir / "CLAUDE.md"
    action = _upsert_delimited_block(claude_md, "workflow", CLAUDE_MD_LLMFLOW_BLOCK)
    click.echo(f"  {action.capitalize()} CLAUDE.md (llmflow-init block)")

    sp_home = Path.home() / ".sp"
    installed = _install_claude_skills(base_dir, sp_home=sp_home)
    if not installed:
        click.echo("  No skills found in ~/.sp/skills/ — none copied into .claude/skills/.")
        return

    click.echo(f"  Installed {len(installed)} skill(s) into .claude/skills/: {', '.join(installed)}")
    click.echo("  Commit .claude/skills/ so a clone of this repo has them.")


def _configure_cursor(base_dir: Path, update: bool) -> None:
    """Configure Cursor via .cursorrules."""
    path = base_dir / ".cursorrules"
    action = _upsert_delimited_block(path, "workflow", CURSORRULES_LLMFLOW_BLOCK)
    click.echo(f"  {action.capitalize()} .cursorrules (llmflow-init block)")


def _configure_windsurf(base_dir: Path, update: bool) -> None:
    """Configure Windsurf via .windsurfrules."""
    path = base_dir / ".windsurfrules"
    action = _upsert_delimited_block(path, "workflow", WINDSURFRULES_LLMFLOW_BLOCK)
    click.echo(f"  {action.capitalize()} .windsurfrules (llmflow-init block)")


def _configure_ai_assistants(base_dir: Path, update: bool = False) -> None:
    """Write every assistant's configuration. Non-interactive by design (#204, D4/D5).

    This function used to open with `if not sys.stdin.isatty(): return`, so CI, Docker
    builds, `sp init < /dev/null` and any scripted onboarding got nothing and were told
    nothing — the exact path a "clone it and it works" story takes. On a TTY it asked
    four questions with `Claude Code` defaulting to *No* and skills behind a second *No*,
    so a user pressing Enter throughout ended up with a silently broken setup.

    Captain, 2026-08-19: *"a fresh clone must get skills."*

    Every write below lands inside `base_dir`, is idempotent, and cannot clobber a file
    the project already owns. With the machine-scoped skill install gone (D1-A′), no
    prompt has anything left to protect, so there are none.
    """
    click.echo("\nConfiguring AI assistants for this project.")

    click.echo("GitHub Copilot:")
    _configure_copilot(base_dir, update)
    click.echo("Claude Code:")
    _configure_claude_code(base_dir, update)
    click.echo("Cursor:")
    _configure_cursor(base_dir, update)
    click.echo("Windsurf:")
    _configure_windsurf(base_dir, update)


def _write_gitignore(base_dir: Path) -> None:
    """Generate `.gitignore` when the project has none (#204, plan D9).

    Captain, 2026-08-19: *"write a .gitignore if it does not exist, but do not overwrite
    an existing one."* A project that already has one owns it; sp does not get to edit
    a file the project has been maintaining.

    The ignored paths are derived from the file catalog rather than written out here, so
    the ignore list cannot disagree with the ownership record. That is what keeps
    `.claude/skills/` out of it: those entries are marked committed, and a fresh clone
    must receive them or it has no slash commands at all.
    """
    from llmflow.file_catalog import project_gitignore_lines

    gitignore = base_dir / ".gitignore"
    if gitignore.exists():
        logger.info(".gitignore already exists; leaving as-is.")
        return

    lines = [
        "# Generated by sp init. Paths are derived from the file catalog",
        "# (llmflow/file_catalog.py) — anything sp marks as committed is absent here,",
        "# including .claude/skills/, which a clone needs in order to have skills.",
        "",
        *project_gitignore_lines(),
        "",
    ]
    gitignore.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Created .gitignore")


AI_OVERVIEW_DOC = """<!-- Generated by sp init -->
# Scripture Pipelines — Repo Overview for AI Assistants

This repository contains Scripture Pipelines pipelines, prompts, and outputs.
It was initialized with the `sp init` command.

## Layout

- `pipelines/` – YAML pipeline definitions
- `prompts/` – prompt templates used by `llm` steps
- `outputs/` – generated artifacts written by `saveas`
- `docs/` – human- and AI-facing documentation
  - `docs/tutorial.md` – walkthrough of the starter pipeline
  - `docs/llmflow-language-quickref.md` – compact language reference

## How AI helpers should use this repo

- Prefer reading `pipelines/` and `prompts/` directly when editing
  flows.
- Use `docs/tutorial.md` to understand the starter example and how
  variables + `saveas` work.
- Use `docs/llmflow-language-quickref.md` for common YAML keys and
  step types; defer to the upstream engine docs for advanced features.
"""

_AI_RULES_FRAME = """<!-- Generated by sp init -->
# AI Assistant Rules for This Repo

These guardrails apply to any language model collaborating on this
Scripture Pipelines-based project.

{rules}
"""


def ai_rules_doc() -> str:
    """The rules document `sp init` writes, rendered from `data/ai-rules.yaml`.

    Call this from inside this module. `AI_RULES_DOC` still works for importers via
    `__getattr__` below, but a module-level `__getattr__` is not consulted for a bare name
    used *within* the module — that raises `NameError`, which is what happened when this was
    first written and what `ruff`'s F821 caught.
    """
    from llmflow.ai_rules import render_numbered

    return _AI_RULES_FRAME.format(rules=render_numbered())


def __getattr__(name: str):
    """Render `AI_RULES_DOC` on first access from the single source (2026-08-21).

    The rules used to be a literal here, and a *different* literal in
    `tools/update_ai_context.py`. Both wrote `docs/ai-context/sp/rules.md`, so which rules a
    project was held to depended on which generator last ran. Now `data/ai-rules.yaml` is the
    only place they are written and both renderers read it.

    Deliberately lazy rather than computed at import. `cli_utils` is imported by every `sp`
    command; a missing or unreadable data file must fail the command that needs the rules,
    not `sp --version`.
    """
    if name == "AI_RULES_DOC":
        return ai_rules_doc()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


GITHUB_WORKFLOW_DOC = """<!-- Generated by sp init -->
# GitHub Issue & Commit Workflow

## Issue Process

### Issues as Design Forum

Issues serve three roles in this project:

1. **Backlog management** — tracking features and bugs
2. **Upstream bug reporting** — documenting problems in dependencies or data sources
3. **Live design forum** — capturing the full trajectory of design decisions

For complex features, design conversations belong in issue threads, not in documents that drift out of sync. The entire history from initial proposal through implementation is preserved in the issue.

**Example pattern** (from discourse-flow nested pericope work):
- Issue #3: The "what" — rhetorical case, proposed schema, triggering conditions
- Issue #5: The "how" — pipeline design, prompt contracts, checkpoint implications

### Issue References in Commits

**Subject line format:**
```
feat: description (#93, #94)
```

**Commit body format:**
```
- Key change 1
- Key change 2
- Key change 3

Issues: #93, #94
Version: X.X.X.XX
```

**Auto-closing issues:**

Use `Closes #XX` or `Fixes #XX` in the commit body to trigger GitHub's automatic issue closure:

```
Enforce prompt contracts at runtime (Issue #96)

Implements runtime validation to prevent undeclared variables in
prompt bodies. Variables used in {{brackets}} must be declared in
the prompt header's 'requires' or 'optional' lists.

Key changes:
- src/llmflow/runner.py: Enhanced render_prompt() with contract enforcement
- tests/test_prompt_contract_enforcement.py: 7 comprehensive test cases

Test coverage: 1770 passed, 12 skipped (7 new tests)

Closes #96
Version: 0.2.1.14
```

When this commit is pushed to GitHub, Issue #96 will automatically close.

## Version Numbering

**CRITICAL:** Always increment the 4th component:
- `0.2.1.13` → `0.2.1.14`
- `0.2.1.14` → `0.2.1.15`

**Never propose minor/major bumps** unless explicitly requested by the user.

Each issue gets one version increment. The 4th component is the atomic unit of change tracking.

## CHANGELOG Updates

Every version in `CHANGELOG.md` documents completed issues:

```markdown
## 0.2.1.14 — 2026-04-02

### New Features

- **Runtime prompt contract enforcement** — Variables used in {{brackets}}
  must be declared in prompt header's 'requires' or 'optional' lists.
  Prevents undeclared variable expansion from context. (Issue #96)

### Test Coverage

- Added `tests/test_prompt_contract_enforcement.py` with 7 comprehensive tests
- Full test suite: **1770 tests passing** (7 new tests added)
```

Issues are referenced with `(Issue #XX)` notation for traceability.

## Using GitHub CLI

**Do NOT assume:**
- GitKraken is configured (MCP tools may not be available)
- Heredoc syntax works (it always corrupts in run_in_terminal)
- Permission to write to `/tmp`, `~/tmp`, or arbitrary directories

**DO use:**
- GitHub CLI (`gh`) for all GitHub operations
- `./tmp/` directory (workspace-relative) for temporary files
- Standard file writes instead of heredocs

**Example - closing an issue:**
```bash
gh issue close 96 --comment "Fixed in v0.2.1.14 - runtime prompt contract enforcement implemented"
```

**Example - viewing issue details:**
```bash
gh issue view 96
```

**Example - temporary file pattern:**
```bash
# Write to workspace-relative tmp/
cat > ./tmp/comment.txt << 'EOF'
Fixed in v0.2.1.14. Runtime prompt contract enforcement now validates that
all variables used in {{brackets}} are declared in the prompt header.
EOF

gh issue comment 96 --body-file ./tmp/comment.txt
```

## Workflow Summary

1. **Create issue** for feature/bug (or it already exists)
2. **Design discussion** in issue thread (for complex work)
3. **Implement** with test-first approach
4. **Commit** with issue reference and `Closes #XX`
5. **Update CHANGELOG** with issue reference `(Issue #XX)`
6. **Push** to trigger auto-close
7. **Verify** issue closed automatically

If auto-close doesn't work, use `gh issue close XX` manually.
"""

SP_OVERVIEW_DOC = """<!-- Generated by sp init -->
# Scripture Pipelines, in brief

This project runs on **Scripture Pipelines** — a declarative pipeline engine for AI-assisted
biblical and linguistic scholarship. The command is `sp`.

## What that means for you

A pipeline is a YAML file: an ordered list of steps, each with named inputs and outputs. The
YAML is the design, not a wrapper around code hidden elsewhere — which is why `sp lint`,
`sp run --dry-run` and `--rewind-to` can each reason about a pipeline without executing it.

- **`sp lint --pipeline <file>`** — check a pipeline before spending anything
- **`sp run --pipeline <file> --dry-run`** — resolve every path and variable, call no model
- **`sp run --pipeline <file>`** — the real thing, which costs money and writes files

`sp run` is never run on an AI's initiative. A human decides when a pipeline runs.

## Where the rest of it is

- **`sp/index.md`** — every document Scripture Pipelines ships, and what each is for
- **`sp/rules.md`** — the rules an AI session in this project is held to
- **`project/`** — this project's own map, description and rules. Yours, not sp's.

Full documentation lives in the engine repository. This file is a pointer, not a manual: it is
regenerated by `sp`, so anything written here is lost on the next update. Project-specific notes
belong in `project/`.
"""

PROJECT_RULES_DOC = """<!-- Created once by sp init. This file is yours; sp never overwrites it. -->
# This project's rules

Constraints that hold in **this** project and nowhere else. `sp` creates this file once and
never touches it again, so it is safe to write here.

## What belongs here

Things an AI session would otherwise get wrong, and that no general rule covers:

- domain constraints — *"never italicise anything that could contain Hebrew text"*
- data facts that change what is correct — *"this dataset's identifiers are not unique"*
- local conventions — naming, layout, what must never be regenerated
- prohibitions with a reason — what went wrong before, so it is not repeated

Write the reason, not only the rule. A constraint whose *why* is missing gets argued with, or
quietly dropped when it becomes inconvenient.

## What does not belong here

- **General practice** — how to run pipelines, how to write prompts, how to use git. That is in
  `sp/rules.md` and in the shipped disciplines, and a copy here would drift from them.
- **What is in flight** — that is `project/TODO.md`.
- **Description** — what this project *is* goes in `project/overview.md`.

## The rules

_(none yet — add them as they are learned)_
"""

AI_PROJECT_DOC = """\
# Project-Specific AI Context

**This file is yours.** `sp init` created it once and will **never overwrite it** — not even on
`sp init --update`. It is the durable, repo-scoped memory every AI assistant working here should
read and keep current. The generated files in `docs/ai-context/` (`sp/index.md`, `project/overview.md`,
`rules.md`, `github-workflow.md`) are refreshed by `sp init --update` — do not hand-edit them;
anything you want to keep and evolve locally goes here or elsewhere under `project/`, which is also
yours and which points assistants at it.

**Discipline (for the AI):** record a non-obvious project fact here the moment you learn it — a
data source, a convention, a trap that cost time. Keep it a scannable map, not a dump; prune
what goes stale. This is the same idea as `/handoff` (session scope) and `~/.sp` (machine
scope), at the repo scope.

The sections below are a starting structure — adapt them to this repo, don't force them.

## What this repo is

<!-- One paragraph: what it does, its domain, who or what it serves. -->

## Data sources & key artifacts

<!-- Where the data lives; canonical files, schemas, pipelines; what is generated vs authored. -->

## Local conventions

<!-- Repo-specific rules not in sp's standard: naming, structure, review norms. -->

## Gotchas / hard-won facts

<!-- Traps and non-obvious facts, recorded as learned (with a file:line or a pointer). -->

## Where active work lives

<!-- Pointers: project/TODO.md (current state), project/plans/ (designs in flight). -->
"""


AI_INDEX_DOC = """<!-- Created once by sp init. This file is yours; sp never overwrites it. -->
# This project's map

**Read this first.** It is *your* map — `sp` wrote it once and will never overwrite it, so add
to it freely.

## Start here, every session

- `project/TODO.md` — active work, what is in flight, what not to touch
- `docs/ai-context/project/project.md` — this project's facts, conventions and gotchas
- `docs/ai-context/project/rules.md` — constraints that hold in this project and nowhere else
- `docs/ai-context/sp/rules.md` — the rules every Scripture Pipelines session is held to

## The two halves of `docs/ai-context/`

| | |
|---|---|
| **`sp/`** | Scripture Pipelines' own documents. Regenerated — do not hand-edit. `sp/index.md` lists them all. |
| **`project/`** | Yours. This map, `overview.md`, `rules.md` and `project.md`. `sp` creates each once and never touches it again. |

The split exists because one directory of mixed ownership meant a project's own notes were
overwritten by an update. Anything you write belongs under `project/`.

## This project's own entry documents

Add them here as the project grows: a HANDOFF, design documents and the warnings that go with
them, a field reference, data notes. Anything a session must read before working here belongs in
this list, or in `project/project.md`, or in a document one of them points to.

- _(add yours here)_

## Machine-level access

Standing permissions for this machine — what an AI may read without being asked each time —
live in `~/.sp/user-context/`, outside any repository. Only the machine's owner grants those.
"""

# A pointer, not a copy (#204, plan D4/A2). See ASSISTANT_RULES_POINTER above for why
# this document no longer restates the rules it used to carry.

VSCODE_DOC = """<!-- Generated by sp init -->
# VS Code Setup for Scripture Pipelines Projects

Recommended settings and the privacy/convenience trade-offs for AI-assisted pipeline work.

## Recommended settings.json

Copy the block below into `.vscode/settings.json` (create the file if it doesn't exist).
Adjust to taste — the comments explain each section.

```json
{
  "files.trimTrailingWhitespace": true,
  "editor.largeFileOptimizations": false,

  // Prevent VS Code from offering to open parent folders as a workspace,
  // which can confuse Copilot about which repo it is in.
  "git.openRepositoryInParentFolders": "never",

  // Stack chat sessions vertically so long conversations are easier to scroll.
  "chat.viewSessions.orientation": "stacked",

  // --- Terminal auto-approve ---
  // Controls which commands Copilot can run in the terminal WITHOUT prompting.
  // Read the privacy section below before enabling anything beyond the defaults.
  "chat.tools.terminal.autoApprove": {

    // Safe read-only commands — approve freely.
    "pwd": true, "ls": true, "dir": true, "echo": true,
    "cat": true, "head": true, "tail": true, "wc": true,
    "nl": true, "grep": true, "rg": true, "find": true,
    "sort": true, "column": true, "date": true,
    "basename": true, "dirname": true, "which": true,
    "file": true, "stat": true,

    // Read-only git commands — approve.
    "/^git\\\\s+status\\\\b/": true,
    "/^git\\\\s+log\\\\b/": true,
    "/^git\\\\s+show\\\\b/": true,
    "/^git\\\\s+diff\\\\b/": true,
    "/^git\\\\s+ls-files\\\\b/": true,
    "/^git\\\\s+grep\\\\b/": true,
    "/^git\\\\s+branch\\\\b$/": true,

    // Commands that change state — keep at false (require confirmation).
    "rm": false, "rmdir": false, "del": false,
    "curl": false, "wget": false,
    "chmod": false, "chown": false,
    "kill": false, "ps": false,

    // Scripting / eval — always false.
    "xargs": false, "eval": false, "jq": false
  }
}
```

## Privacy vs. convenience

`chat.tools.terminal.autoApprove` is a direct trade-off:

**More approvals = less friction, more exposure.**

| Risk | What it means |
|---|---|
| **Read commands are safe** | `ls`, `cat`, `grep` etc. only read from your disk. Approving them just saves a click. |
| **Write/delete commands are not** | `rm`, `del` can destroy work. Always require confirmation. |
| **Network commands are not** | `curl`, `wget`, `Invoke-WebRequest` can exfiltrate data or download malicious payloads. Always require confirmation. |
| **`eval` / `Invoke-Expression` are never safe** | These can run arbitrary generated code without any further prompt. Never approve. |
| **`cd` is subtle** | Changing directory mid-session can cause Copilot to operate in the wrong scope. Leave at false. |

**The recommended config above approves only read-only commands.** This eliminates most confirmation dialogs during normal pipeline development (reading files, checking git status) while keeping every state-changing operation behind a prompt.

If you are working on a project with sensitive content (Bible translations, proprietary data), be aware that even read-only auto-approval means Copilot can scan any file in the workspace and include it in its context window. That is intentional for pipeline development but worth understanding.
"""

PROJECT_TODO = """# Project TODO

## 🔥 Active
- [ ]

## 📋 Backlog

### 🎓 Tutorial: get started with AI + GitHub issues

- [ ] Run the hello pipeline: `sp run --pipeline pipelines/hello.yaml`
- [ ] Explore the pipeline: open `pipelines/hello.yaml` in VS Code and use Copilot `/explain` on the file contents
- [ ] Explore the prompts: open each file in `prompts/` and use `/explain` to understand the frontmatter contract and prompt template
- [ ] Brainstorm extensions: ask GitHub Copilot "What are some interesting ways I could modify or extend this pipeline?"
- [ ] Extend the pipeline: implement one new idea with AI assistance — new step, new prompt, or modified variable
- [ ] Debug a run: introduce an error, run the pipeline, paste the terminal output into Copilot and ask it to diagnose and fix
- [ ] Triage: review open GitHub issues on this repo and close any that have been addressed
- [ ] Plan next steps: ask Copilot "Look at the open issues and what we have done so far. What should we work on next?"

## ✅ Done

---
_Audit notes and QA reports → project/audits/_
_Pipeline decisions → project/decisions.md (create when needed)_
"""

PROJECT_AUDITS_README = """<!-- Generated by sp init -->
# Audits

Store pipeline QA reports, output review notes, and lint snapshots here.

## Suggested naming

```
YYYY-MM-DD_<passage-or-scope>_<pipeline-or-step>.md
```

Examples:
- `2026-03-17_Ruth-1_storyflow-psalms.md`
- `2026-03-18_full-run_semlex-multipass.md`

## What belongs here

- Manual review of LLM outputs (correctness, tone, coverage)
- Notes on specific failures and how they were resolved
- Before/after comparisons when a prompt or pipeline changes
- Coverage validator reports

## What does not belong here

- Pipeline YAML files → `pipelines/`
- Generated artifacts → `outputs/`
- Active tasks → `project/TODO.md`
"""

DOCS_AUDITS_INDEX = """<!-- Generated by sp init -->
# Audit Dispatch

**What this file does:** Maps artifact types to their audit checklist files. When you need to audit something, find its row below, use the trigger phrase listed, and the AI assistant will open the corresponding procedure file before evaluating your artifact.

## Dispatch Table

| What you have | Say | Open |
|---|---|---|
| Passage output `.md` | "audit this passage" | `audit-passage.md` |
| Leader's guide `.md` | "audit this per the checklist" | `audit-leadersguide.md` |

## Adding New Audit Procedures

1. Create a new checklist file in this directory (e.g. `audit-my-artifact.md`)
2. Keep it 20–60 lines max
3. Use `- [ ]` checkbox format only — no explanatory prose
4. Put STOP conditions in bold at the top
5. Add a row to the table above with the trigger phrase

## Audit Records

Audit findings go in `project/audits/`, not here. One file per audit run:
- `project/audits/audit-MRK-6-14-29.md`
- `project/audits/audit-LUK-1-full-pipeline.md`

This directory (`docs/audits/`) contains only **procedures** (version-controlled, reusable). Records (`project/audits/`) are **findings** (per-run, not committed).
"""

AUDIT_PASSAGE_CHECKLIST = """<!-- Generated by sp init -->
# Audit Checklist: Passage Output

**STOP conditions (abort if any fail):**
- **STOP** if passage reference is missing or malformed
- **STOP** if output file is empty or contains only template markers

## Structure & Completeness

- [ ] Passage reference is correct (book, chapter, verses)
- [ ] All expected sections are present (introduction, analysis, application, etc.)
- [ ] No placeholder text remains (e.g., `[TODO]`, `[FILL IN]`)
- [ ] Section headings match pipeline specification

## Content Quality

- [ ] Introduction accurately summarizes the passage
- [ ] Analysis addresses the key theological or narrative points
- [ ] Application is contextually appropriate
- [ ] Cross-references are accurate (if present)
- [ ] Cultural notes are factually correct (if present)

## Format & Rendering

- [ ] Markdown syntax is valid (no broken links, malformed headers)
- [ ] Scripture quotations are properly formatted
- [ ] Lists and bullets render correctly
- [ ] No LLM artifacts (e.g., "As an AI assistant...")

## Pipeline Metadata

- [ ] Output filename matches expected pattern
- [ ] File saved to correct directory per pipeline spec
- [ ] Timestamp or version info is present (if required)

## Record findings in `project/audits/audit-<passage>-<date>.md`
"""

AUDIT_LEADERSGUIDE_CHECKLIST = """<!-- Generated by sp init -->
# Audit Checklist: Leader's Guide

**STOP conditions (abort if any fail):**
- **STOP** if passage reference is missing
- **STOP** if file contains only boilerplate/"coming soon" text
- **STOP** if critical sections (Discussion Questions) are missing

## Structural Completeness

- [ ] Passage reference is correct
- [ ] Introduction/Overview section is present
- [ ] Discussion questions section is present
- [ ] Application section is present
- [ ] Closing/Prayer section is present (if required)

## Discussion Questions

- [ ] At least 3 discussion questions provided
- [ ] Questions are open-ended (not yes/no)
- [ ] Questions connect to passage content
- [ ] Questions appropriate for target audience
- [ ] No leading or tendentious questions

## Content Accuracy

- [ ] Introduction accurately summarizes passage
- [ ] No theological errors or misrepresentations
- [ ] Cultural/historical notes are factually correct
- [ ] Cross-references are accurate
- [ ] Application is contextually appropriate

## Usability for Leaders

- [ ] Language is accessible (no jargon without explanation)
- [ ] Instructions for group leader are clear
- [ ] Timing estimates are realistic (if provided)
- [ ] Materials list is complete (if provided)

## Format & Polish

- [ ] Markdown syntax is valid
- [ ] No LLM artifacts ("As an AI...")
- [ ] Scripture quotations properly formatted
- [ ] Headings follow project style guide

## Record findings in `project/audits/audit-leadersguide-<passage>-<date>.md`
"""


def _lock_sp_dir(path: Path) -> None:
    """Remove write permission from path and all contents (owner, group, others)."""
    if not path.exists():
        return
    for item in [path, *path.rglob("*")]:
        item.chmod(item.stat().st_mode & ~stat.S_IWUSR & ~stat.S_IWGRP & ~stat.S_IWOTH)


def _unlock_sp_dir(path: Path) -> None:
    """Restore owner write permission on path and all contents."""
    if not path.exists():
        return
    for item in [path, *path.rglob("*")]:
        item.chmod(item.stat().st_mode | stat.S_IWUSR)


@contextmanager
def _sp_dir_writable(path: Path):
    """Unlock a protected ~/.sp/ directory for writing, then re-lock when done."""
    was_locked = path.exists() and not os.access(path, os.W_OK)
    if was_locked:
        _unlock_sp_dir(path)
    try:
        yield
    finally:
        if path.exists():
            _lock_sp_dir(path)


def install_global_disciplines(sp_home: Optional[Path] = None, force: bool = False) -> None:
    """Install global disciplines to ~/.sp/disciplines/.

    Args:
        sp_home: Override ~/.sp directory (for testing). Defaults to Path.home() / ".sp"
        force: If True, overwrite existing files. If False, skip existing files.
    """
    if sp_home is None:
        sp_home = Path.home() / ".sp"

    disciplines_dir = sp_home / "disciplines"
    with _sp_dir_writable(disciplines_dir):
        disciplines_dir.mkdir(parents=True, exist_ok=True)

        # Get templates from package
        import llmflow
        pkg_root = Path(llmflow.__file__).parent
        templates_dir = pkg_root / "templates" / "sp-disciplines"

        # Copy convention files
        for template_file in templates_dir.glob("*.md"):
            target_file = disciplines_dir / template_file.name

            if target_file.exists() and not force:
                logger.info(f"{target_file.name} already exists in ~/.sp/disciplines/; skipping")
                continue

            content = template_file.read_text(encoding="utf-8")
            target_file.write_text(content, encoding="utf-8")
            logger.info(f"✓ Installed {template_file.name} to ~/.sp/disciplines/")

    # Files that belong at the root of ~/.sp/, not in a subdirectory (#204).
    # drift-patterns.md is read by the load-context skill as ~/.sp/drift-patterns.md,
    # so its location is part of a contract and cannot be moved under disciplines/.
    root_templates_dir = pkg_root / "templates" / "sp-root"
    if root_templates_dir.is_dir():
        sp_home.mkdir(parents=True, exist_ok=True)

        # Deliberately NOT _sp_dir_writable(): that helper locks its directory on exit
        # unconditionally, even when it was writable beforehand. Applied to the ~/.sp
        # root it left the whole tree read-only, so the install_global_skills() call
        # that follows in init_project() failed — and failed silently, because that
        # call sits inside a try/except that only warns. Restore the prior state
        # instead of imposing one.
        was_locked = not os.access(sp_home, os.W_OK)
        if was_locked:
            _unlock_sp_dir(sp_home)
        try:
            for template_file in sorted(root_templates_dir.glob("*.md")):
                target_file = sp_home / template_file.name

                if target_file.exists() and not force:
                    logger.info(f"{target_file.name} already exists in ~/.sp/; skipping")
                    continue

                target_file.write_text(
                    template_file.read_text(encoding="utf-8"), encoding="utf-8"
                )
                logger.info(f"✓ Installed {template_file.name} to ~/.sp/")
        finally:
            if was_locked:
                _lock_sp_dir(sp_home)


def install_global_skills(sp_home: Optional[Path] = None, force: bool = False) -> None:
    """Install global skills to ~/.sp/skills/.

    Args:
        sp_home: Override ~/.sp directory (for testing). Defaults to Path.home() / ".sp"
        force: If True, overwrite existing files. If False, skip existing files.
    """
    if sp_home is None:
        sp_home = Path.home() / ".sp"

    import llmflow
    pkg_root = Path(llmflow.__file__).parent
    templates_dir = pkg_root / "templates" / "sp-skills"
    skills_dir = sp_home / "skills"

    with _sp_dir_writable(skills_dir):
        for skill_dir in sorted(templates_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            skill_file = skill_dir / "SKILL.md"
            if not skill_file.exists():
                continue

            target_dir = sp_home / "skills" / skill_dir.name
            target_dir.mkdir(parents=True, exist_ok=True)
            target = target_dir / "SKILL.md"

            if target.exists() and not force:
                logger.info(f"{skill_dir.name} already exists in ~/.sp/skills/; skipping")
                continue

            target.write_text(skill_file.read_text(encoding="utf-8"), encoding="utf-8")
            logger.info(f"✓ Installed {skill_dir.name} skill to ~/.sp/skills/")


# `_fetch_stand_down` used to pull stand-down/SKILL.md from human-at-the-helm at install
# time, treating the shipped template as a fallback. Removed 2026-08-19 (#204, plan D10).
#
# Why: D10 makes `sp doctor` restore any sp-owned file whose content has diverged from
# what the package ships. A file deliberately fetched from elsewhere diverges by design,
# so doctor would have overwritten the fetched copy with the bundled one on every run.
# Captain's ruling: *"Drop the fetch — ship stand-down like every other skill, one source
# of truth."*
#
# The bundled template is the later of the two — it carries "Propose a Fix" (wait for
# approval before writing any file) and a Step 3 that the upstream copy does not.


def init_project(base_dir: Path, update: bool = False, no_examples: bool = False) -> None:
    """Initialize a new Scripture Pipelines project structure.

    When update=True, regenerate any file that carries the
    '<!-- Generated by sp init -->' marker, leaving hand-edited
    files untouched.

    When no_examples=True, skip the 5 starter example files
    (hello.gpt, reply.gpt, hello-llmflow.yaml, hello.yaml,
    tutorial.md) — directories and structural files are still created.
    """
    prompts_dir = base_dir / "prompts"
    pipelines_dir = base_dir / "pipelines"
    output_dir = base_dir / "outputs"
    docs_dir = base_dir / "docs"
    ai_context_dir = docs_dir / "ai-context"
    sp_context_dir = ai_context_dir / "sp"
    project_context_dir = ai_context_dir / "project"
    docs_audits_dir = docs_dir / "audits"
    project_dir = base_dir / "project"
    audits_dir = project_dir / "audits"
    vscode_dir = base_dir / ".vscode"

    prompts_dir.mkdir(parents=True, exist_ok=True)
    pipelines_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)
    ai_context_dir.mkdir(parents=True, exist_ok=True)
    sp_context_dir.mkdir(parents=True, exist_ok=True)
    project_context_dir.mkdir(parents=True, exist_ok=True)
    docs_audits_dir.mkdir(parents=True, exist_ok=True)
    project_dir.mkdir(parents=True, exist_ok=True)
    audits_dir.mkdir(parents=True, exist_ok=True)
    vscode_dir.mkdir(parents=True, exist_ok=True)

    prompt_path = prompts_dir / "hello.gpt"
    reply_prompt_path = prompts_dir / "reply.gpt"
    pipeline_path = pipelines_dir / "hello-llmflow.yaml"
    hello_yaml_path = pipelines_dir / "hello.yaml"
    tutorial_doc_path = docs_dir / "tutorial.md"
    language_quickref_path = docs_dir / "llmflow-language-quickref.md"
    vscode_doc_path = docs_dir / "vscode.md"
    ai_overview_path = project_context_dir / "overview.md"
    ai_rules_path = sp_context_dir / "rules.md"
    ai_project_index_path = project_context_dir / "index.md"
    sp_index_path = sp_context_dir / "index.md"
    ai_github_workflow_path = sp_context_dir / "github-workflow.md"
    ai_project_path = project_context_dir / "project.md"
    sp_overview_path = sp_context_dir / "overview.md"
    project_rules_path = project_context_dir / "rules.md"
    docs_audits_index_path = docs_audits_dir / "INDEX.md"
    audit_passage_path = docs_audits_dir / "audit-passage.md"
    audit_leadersguide_path = docs_audits_dir / "audit-leadersguide.md"
    project_todo_path = project_dir / "TODO.md"
    project_audits_readme_path = audits_dir / "README.md"

    if not no_examples:
        if not prompt_path.exists():
            prompt_path.write_text(HELLO_PROMPT, encoding="utf-8")
            logger.info("Created prompts/hello.gpt")
        elif update and _is_generated(prompt_path):
            prompt_path.write_text(HELLO_PROMPT, encoding="utf-8")
            logger.info("Updated prompts/hello.gpt")
        else:
            logger.info("prompts/hello.gpt already exists; leaving as-is.")

        if not reply_prompt_path.exists():
            reply_prompt_path.write_text(HELLO_REPLY_PROMPT, encoding="utf-8")
            logger.info("Created prompts/reply.gpt")
        elif update and _is_generated(reply_prompt_path):
            reply_prompt_path.write_text(HELLO_REPLY_PROMPT, encoding="utf-8")
            logger.info("Updated prompts/reply.gpt")
        else:
            logger.info("prompts/reply.gpt already exists; leaving as-is.")

        if not pipeline_path.exists():
            pipeline_path.write_text(HELLO_PIPELINE, encoding="utf-8")
            logger.info("Created pipelines/hello-llmflow.yaml")
        elif update and _is_generated(pipeline_path):
            pipeline_path.write_text(HELLO_PIPELINE, encoding="utf-8")
            logger.info("Updated pipelines/hello-llmflow.yaml")
        else:
            logger.info("pipelines/hello-llmflow.yaml already exists; leaving as-is.")

        if not hello_yaml_path.exists():
            hello_yaml_path.write_text(HELLO_YAML, encoding="utf-8")
            logger.info("Created pipelines/hello.yaml")
        elif update and _is_generated(hello_yaml_path):
            hello_yaml_path.write_text(HELLO_YAML, encoding="utf-8")
            logger.info("Updated pipelines/hello.yaml")
        else:
            logger.info("pipelines/hello.yaml already exists; leaving as-is.")

        if not tutorial_doc_path.exists():
            tutorial_doc_path.write_text(TUTORIAL_DOC, encoding="utf-8")
            logger.info("Created docs/tutorial.md")
        elif update and _is_generated(tutorial_doc_path):
            tutorial_doc_path.write_text(TUTORIAL_DOC, encoding="utf-8")
            logger.info("Updated docs/tutorial.md")
        else:
            logger.info("docs/tutorial.md already exists; leaving as-is.")

    if not language_quickref_path.exists():
        language_quickref_path.write_text(LANGUAGE_QUICKREF_DOC, encoding="utf-8")
        logger.info("Created docs/llmflow-language-quickref.md")
    elif update and _is_generated(language_quickref_path):
        language_quickref_path.write_text(LANGUAGE_QUICKREF_DOC, encoding="utf-8")
        logger.info("Updated docs/llmflow-language-quickref.md")
    else:
        logger.info("docs/llmflow-language-quickref.md already exists; leaving as-is.")

    if not ai_overview_path.exists():
        ai_overview_path.write_text(AI_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/project-overview.md")
    elif update and _is_generated(ai_overview_path):
        ai_overview_path.write_text(AI_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/project-overview.md")
    else:
        logger.info("docs/ai-context/project-overview.md already exists; leaving as-is.")

    if not ai_rules_path.exists():
        ai_rules_path.write_text(ai_rules_doc(), encoding="utf-8")
        logger.info("Created docs/ai-context/sp/rules.md")
    elif update and _is_generated(ai_rules_path):
        ai_rules_path.write_text(ai_rules_doc(), encoding="utf-8")
        logger.info("Updated docs/ai-context/sp/rules.md")
    else:
        logger.info("docs/ai-context/sp/rules.md already exists; leaving as-is.")

    # project/index.md is the project's own map — created once, never overwritten (Q1).
    if not ai_project_index_path.exists():
        ai_project_index_path.write_text(AI_INDEX_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/project/index.md")
    else:
        logger.info("docs/ai-context/project/index.md already exists; leaving as-is (yours to own).")

    # sp/index.md is rendered from data/file-catalog.yaml, so there is no second list.
    from llmflow.file_catalog import render_sp_index

    sp_index_text = render_sp_index()
    if not sp_index_path.exists() or sp_index_path.read_text(encoding="utf-8") != sp_index_text:
        sp_index_path.write_text(sp_index_text, encoding="utf-8")
        logger.info("Wrote docs/ai-context/sp/index.md (rendered from the file catalog)")

    if not ai_github_workflow_path.exists():
        ai_github_workflow_path.write_text(GITHUB_WORKFLOW_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/github-workflow.md")
    elif update and _is_generated(ai_github_workflow_path):
        ai_github_workflow_path.write_text(GITHUB_WORKFLOW_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/github-workflow.md")
    else:
        logger.info("docs/ai-context/github-workflow.md already exists; leaving as-is.")

    # sp's own overview: ours, refreshed like the rest of sp/.
    if not sp_overview_path.exists():
        sp_overview_path.write_text(SP_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/sp/overview.md")
    elif update:
        sp_overview_path.write_text(SP_OVERVIEW_DOC, encoding="utf-8")
        logger.info("Updated docs/ai-context/sp/overview.md")

    # The project's own rules — created once, never overwritten. The file whose absence sent
    # project-specific constraints into an invisible memory store.
    if not project_rules_path.exists():
        project_rules_path.write_text(PROJECT_RULES_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/project/rules.md")
    else:
        logger.info("docs/ai-context/project/rules.md already exists; leaving as-is (yours to own).")

    # project.md is the consumer's own lane — created once, never overwritten (even on --update).
    if not ai_project_path.exists():
        ai_project_path.write_text(AI_PROJECT_DOC, encoding="utf-8")
        logger.info("Created docs/ai-context/project/project.md")
    else:
        logger.info("docs/ai-context/project/project.md already exists; leaving as-is (yours to own).")

    if not vscode_doc_path.exists():
        vscode_doc_path.write_text(VSCODE_DOC, encoding="utf-8")
        logger.info("Created docs/vscode.md")
    elif update and _is_generated(vscode_doc_path):
        vscode_doc_path.write_text(VSCODE_DOC, encoding="utf-8")
        logger.info("Updated docs/vscode.md")
    else:
        logger.info("docs/vscode.md already exists; leaving as-is.")

    # project/TODO.md — never overwritten; hand-edited from first run
    if not project_todo_path.exists():
        project_todo_path.write_text(PROJECT_TODO, encoding="utf-8")
        logger.info("Created project/TODO.md")
    else:
        logger.info("project/TODO.md already exists; leaving as-is.")

    if not project_audits_readme_path.exists():
        project_audits_readme_path.write_text(PROJECT_AUDITS_README, encoding="utf-8")
        logger.info("Created project/audits/README.md")
    elif update and _is_generated(project_audits_readme_path):
        project_audits_readme_path.write_text(PROJECT_AUDITS_README, encoding="utf-8")
        logger.info("Updated project/audits/README.md")
    else:
        logger.info("project/audits/README.md already exists; leaving as-is.")

    if not docs_audits_index_path.exists():
        docs_audits_index_path.write_text(DOCS_AUDITS_INDEX, encoding="utf-8")
        logger.info("Created docs/audits/INDEX.md")
    elif update and _is_generated(docs_audits_index_path):
        docs_audits_index_path.write_text(DOCS_AUDITS_INDEX, encoding="utf-8")
        logger.info("Updated docs/audits/INDEX.md")
    else:
        logger.info("docs/audits/INDEX.md already exists; leaving as-is.")

    if not audit_passage_path.exists():
        audit_passage_path.write_text(AUDIT_PASSAGE_CHECKLIST, encoding="utf-8")
        logger.info("Created docs/audits/audit-passage.md")
    elif update and _is_generated(audit_passage_path):
        audit_passage_path.write_text(AUDIT_PASSAGE_CHECKLIST, encoding="utf-8")
        logger.info("Updated docs/audits/audit-passage.md")
    else:
        logger.info("docs/audits/audit-passage.md already exists; leaving as-is.")

    if not audit_leadersguide_path.exists():
        audit_leadersguide_path.write_text(AUDIT_LEADERSGUIDE_CHECKLIST, encoding="utf-8")
        logger.info("Created docs/audits/audit-leadersguide.md")
    elif update and _is_generated(audit_leadersguide_path):
        audit_leadersguide_path.write_text(AUDIT_LEADERSGUIDE_CHECKLIST, encoding="utf-8")
        logger.info("Updated docs/audits/audit-leadersguide.md")
    else:
        logger.info("docs/audits/audit-leadersguide.md already exists; leaving as-is.")

    logger.info("Output directory ready at ./outputs")

    # Install global disciplines to ~/.sp/ (non-interactive, no machine-scoped UI needed)
    try:
        install_global_disciplines(force=update)
        install_global_skills(force=update)
    except Exception as e:
        logger.warning(f"Could not install global resources to ~/.sp/: {e}")

    # Written before the assistant files so .claude/skills/ is never briefly untracked.
    _write_gitignore(base_dir)

    # AI assistant configuration — all project-scoped, no prompts (D4/D5)
    _configure_ai_assistants(base_dir, update=update)

    # Register project and index ai-context files in ~/.sp/ (Issue #132)
    _register_in_global_registry(base_dir)


def _register_in_global_registry(base_dir: Path) -> None:
    """Register the project and its ai-context files in ~/.sp/ (Issue #132).

    Idempotent — skips entries that are already registered.
    """
    import re

    try:
        from llmflow.registry import Registry

        registry_dir = Path.home() / ".sp"
        projects_dir = registry_dir / "projects"
        registry = Registry(registry_dir)

        project_name = base_dir.name
        project_path = str(base_dir.resolve())

        with _sp_dir_writable(projects_dir):
            # Register the project
            if registry.projects.get(project_name) is None:
                registry.projects.register(name=project_name, path=project_path)
                logger.info(f"Registered project '{project_name}' in ~/.sp/projects/")
            else:
                logger.info(f"Project '{project_name}' already registered in ~/.sp/")

        # Index docs/ai-context/*.md files
        ai_context_dir = base_dir / "docs" / "ai-context"
        if ai_context_dir.exists():
            # rglob, not glob: the context is two directories deep since the sp/ and project/
            # split, and a flat glob silently indexed nothing.
            for md_file in sorted(ai_context_dir.rglob("*.md")):
                # Key by the relative path, flattened. Since the sp/ and project/ split there
                # are two `index.md` files and two `overview.md` files, so a bare filename
                # registers one and silently drops the other. The separator is flattened to a
                # hyphen because the registry stores each entry as `<key>.yaml`, and a slash in
                # the key would need a subdirectory that is never created — which failed
                # silently and indexed nothing at all.
                file_key = md_file.relative_to(ai_context_dir).as_posix().replace("/", "-")
                if registry.ai_context.get(file_key) is not None:
                    continue  # already indexed

                # Extract description from first ATX heading in the file
                description = f"AI context: {md_file.stem}"
                try:
                    content = md_file.read_text(encoding="utf-8")
                    for line in content.splitlines():
                        stripped = line.strip()
                        if stripped.startswith("#"):
                            description = re.sub(r"^#+\s*", "", stripped)
                            break
                except OSError:
                    pass

                # Derive topics from filename parts
                topics = [p for p in re.split(r"[-_./]", file_key.removesuffix(".md")) if p]
                topics.append("ai-context")

                registry.ai_context.register(
                    file=file_key,
                    project=project_name,
                    description=description,
                    topics=topics,
                    path=str(md_file.resolve()),
                )
                logger.info(f"Indexed {file_key} in ~/.sp/ai-context/")

    except Exception as e:
        logger.warning(f"Could not register in global registry: {e}")
        logger.warning("This is not critical - registry can be updated manually.")


def list_pipelines(directory: str) -> list[str]:
    """List all YAML pipeline files in a directory."""
    base = Path(directory)
    if not base.exists():
        return []
    pipelines: list[str] = []
    for pattern in ("*.yaml", "*.yml"):
        for path in base.rglob(pattern):
            if path.is_file():
                pipelines.append(str(path.relative_to(base)))
    return sorted(dict.fromkeys(pipelines))


def sync_ai_context_files(base_dir: Path) -> None:
    """Copy ai-context files from the installed Scripture Pipelines package to the consumer repo.

    Files are copied to .github/ai-context/ in the consumer repo.
    This allows consumer repos to reference the canonical AI context files
    without manually copying them or keeping them in sync.
    """
    import importlib.resources
    import shutil

    # Target directory in consumer repo
    target_dir = base_dir / ".github" / "ai-context"
    target_dir.mkdir(parents=True, exist_ok=True)

    # Python 3.9+ uses importlib.resources.files()
    try:
        # Try Python 3.9+ API - docs are packaged under llmflow/docs/
        docs_root = importlib.resources.files("llmflow").joinpath("docs")

        # Copy ai-context files
        ai_context_source = docs_root.joinpath("ai-context")
        if ai_context_source.is_dir():
            for item in ai_context_source.iterdir():
                if item.is_file() and Path(str(item)).suffix == ".md":
                    target_file = target_dir / item.name
                    # Read and write to handle package resources properly
                    content = item.read_text(encoding="utf-8")
                    target_file.write_text(content, encoding="utf-8")
                    logger.info(f"Synced .github/ai-context/{item.name}")

        # Copy audits/ directory files
        audits_source = docs_root.joinpath("audits")
        audits_target = base_dir / ".github" / "ai-context" / "audits"
        audits_target.mkdir(parents=True, exist_ok=True)

        if audits_source.is_dir():
            for item in audits_source.iterdir():
                if item.is_file() and Path(str(item)).suffix == ".md":
                    target_file = audits_target / item.name
                    content = item.read_text(encoding="utf-8")
                    target_file.write_text(content, encoding="utf-8")
                    logger.info(f"Synced .github/ai-context/audits/{item.name}")

    except (AttributeError, TypeError):
        # Fallback for older Python or if files() doesn't work
        logger.warning("Could not sync ai-context files from installed package.")
        logger.warning("This feature requires Python 3.9+ or a properly installed Scripture Pipelines package.")
    except Exception as e:
        logger.error(f"Error syncing ai-context files: {e}")

    logger.info("AI context sync complete. Files copied to .github/ai-context/")