"""`sp doctor` — verify this machine is set up correctly, and fix what sp owns (#204).

Why this exists: nothing on the machine could answer *"is this set up correctly?"*. A
contributor ran `sp init`, then `/load-context`, and the first symptom of a broken setup
was an error that named nothing at all.

Design rules, from `project/plans/design-onboarding-fresh-clone.md`:

- **Expectations are derived from the shipped package**, never from a list kept here. A
  second list drifts, which is exactly how three conventions went unshipped for months.
- **Ownership is read from the file catalog** (`llmflow.file_catalog`, plan D7), not from
  sniffing `<!-- Generated by sp init -->`. That marker's text had already drifted in
  shipped code.
- **`doctor` repairs what sp owns** (plan D10). Captain, 2026-08-19: *"projects have a
  place to write their own context, and it's not in the standard context files that we
  write. we own those. they should not diverge. Report it with a warning and fix it,
  clearly saying that we are doing so."* And: *"Warn, repair, and say you repaired it."*

  A self-repaired file is not a machine fault, so a repair is a WARNING and the command
  still exits 0. ERROR is kept for what `doctor` cannot fix: a build shipping no
  templates, or a repair that fails to write.

- **What repair covers.** `~/.sp` is sp's own directory, so a file there is restored when
  it is missing *or* when its content has diverged. In a project, a catalogued file is
  restored when it has diverged — but a file that is simply absent is left alone and
  reported with its remedy. Creating project files that were never there is `sp init`'s
  job, not a repair; a project with no `docs/ai-context/` is not a project whose files
  have drifted.

- **A missing `CLAUDE.md` is INFO, not a failure** (D3-A). The skill reads it only if
  present, and it is gitignored by convention, so a clone never has one.
- **`~/.sp/user-context/` is not checked at all** (D6). Those files grant an AI standing
  access to a machine; only the machine's owner can grant that, so their absence is the
  correct default rather than a misconfiguration.
- **`docs/ai-context/project.md` is never written.** It is the one file a project is
  invited to own, and a repair pass that covered it would delete the project's own work.

Known overlap: `sp registry status` also reports on `~/.sp/`. Whether `doctor` subsumes it
is tracked in #205; this command consolidates nothing.
"""

from __future__ import annotations

import enum
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from llmflow import paths as _paths
from typing import Optional

from llmflow.file_catalog import Entry, Scope, Source, managed_by_doctor, shipped_content, shipped_path


class Severity(enum.Enum):
    OK = "ok"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


_MARK = {
    Severity.OK: "✓",
    Severity.INFO: "·",
    Severity.WARNING: "!",
    Severity.ERROR: "✗",
}


@dataclass
class Check:
    id: str
    title: str
    severity: Severity
    detail: str = ""
    remedy: str = ""
    repaired: bool = False
    """True when doctor restored the files this check covers (D10)."""


@dataclass
class Report:
    checks: list[Check] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(c.severity is Severity.ERROR for c in self.checks)

    @property
    def exit_code(self) -> int:
        return 0 if self.ok else 1

    def render(self) -> str:
        lines = ["Scripture Pipelines — machine check", ""]
        for check in self.checks:
            lines.append(f"  {_MARK[check.severity]} {check.title}")
            if check.detail:
                lines.append(f"      {check.detail}")
            if check.remedy and check.severity in (Severity.ERROR, Severity.WARNING):
                lines.append(f"      → {check.remedy}")
        lines.append("")

        errors = sum(1 for c in self.checks if c.severity is Severity.ERROR)
        repaired = sum(1 for c in self.checks if c.repaired)
        warnings = sum(
            1 for c in self.checks if c.severity is Severity.WARNING and not c.repaired
        )

        if errors:
            lines.append(f"{errors} problem(s) found.")
        else:
            lines.append("No problems found.")
        if repaired:
            lines.append(
                f"{repaired} check(s) restored files sp owns — see the detail above for what changed."
            )
        if warnings:
            lines.append(f"{warnings} warning(s).")
        return "\n".join(lines)


def _templates_dir() -> Path:
    import llmflow

    return Path(llmflow.__file__).parent / "templates"


def _shipped_names(subdir: str) -> set[str]:
    d = _templates_dir() / subdir
    if not d.is_dir():
        return set()
    return {p.name for p in d.glob("*.md")}


def _shipped_skill_names() -> set[str]:
    d = _templates_dir() / "sp" / "skills"
    if not d.is_dir():
        return set()
    return {p.name for p in d.iterdir() if (p / "SKILL.md").exists()}


def _unlocked(path: Path):
    """Make `path`'s directory writable for a write, restoring the prior state after.

    `install_global_disciplines` locks `~/.sp/disciplines` on exit, so a repair writes
    into a read-only directory. Restoring the previous state rather than imposing one is
    deliberate: unconditionally re-locking is what left the whole `~/.sp` tree read-only
    and broke `install_global_skills()` silently.
    """
    import contextlib
    import os

    from llmflow.cli_utils import _lock_sp_dir, _unlock_sp_dir

    @contextlib.contextmanager
    def _ctx():
        targets = [p for p in (path, path.parent) if p.exists()]
        locked = [p for p in targets if not os.access(p, os.W_OK)]
        for p in locked:
            _unlock_sp_dir(p)
        try:
            yield
        finally:
            for p in locked:
                if p.exists():
                    _lock_sp_dir(p)

    return _ctx()


def _restore(entry: Entry, target: Path) -> None:
    """Write `entry`'s shipped content to `target`. Raises if it cannot.

    Kept module-level and small so a failed repair is easy to simulate in tests, and so
    the failure surfaces as an ERROR rather than being swallowed.
    """
    source = shipped_path(entry)
    if source is not None and source.is_dir():
        with _unlocked(target):
            if target.exists():
                shutil.rmtree(target)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(source, target)
        return

    content = shipped_content(entry)
    if content is None:
        raise ValueError(f"{entry.path} has no shipped content to restore")

    if entry.block:
        # sp owns its block, not the file. Replacing the whole file here would discard
        # whatever the project keeps around it.
        from llmflow.cli_utils import _upsert_delimited_block

        with _unlocked(target):
            target.parent.mkdir(parents=True, exist_ok=True)
            _upsert_delimited_block(target, entry.block, content)
        return

    with _unlocked(target):
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            target.chmod(0o644)
        target.write_text(content, encoding="utf-8")


def _diverged(entry: Entry, target: Path) -> bool:
    """True when an existing target's content differs from what the package ships."""
    source = shipped_path(entry)
    if source is not None and source.is_dir():
        for shipped_file in sorted(source.rglob("*")):
            if shipped_file.is_dir():
                continue
            counterpart = target / shipped_file.relative_to(source)
            if not counterpart.is_file():
                return True
            if counterpart.read_bytes() != shipped_file.read_bytes():
                return True
        return False

    content = shipped_content(entry)
    if content is None:
        return False

    if entry.block:
        from llmflow.cli_utils import read_delimited_block

        return read_delimited_block(target, entry.block) != content

    try:
        return target.read_text(encoding="utf-8") != content
    except OSError:
        return True


def _repair_group(
    entries: list[Entry],
    root: Path,
    restore_when_absent: bool,
) -> tuple[list[str], list[str], list[str]]:
    """Restore the entries that need it.

    Returns (restored, failed, still_missing) as lists of catalog paths.
    """
    restored: list[str] = []
    failed: list[str] = []
    still_missing: list[str] = []

    for entry in entries:
        target = root / entry.path
        exists = target.exists()

        if not exists and not restore_when_absent:
            still_missing.append(entry.path)
            continue
        if exists and not _diverged(entry, target):
            continue

        try:
            _restore(entry, target)
            restored.append(entry.path)
        except Exception:
            failed.append(entry.path)

    return restored, failed, still_missing


def _group_check(
    check_id: str,
    label: str,
    entries: list[Entry],
    root: Path,
    total: int,
    restore_when_absent: bool = True,
    remedy: str = "Run `sp init --update`.",
) -> Check:
    if not total:
        return Check(
            check_id,
            f"{label}: none shipped by this build",
            Severity.WARNING,
            detail="The installed package ships none of these; this build looks incomplete.",
            remedy="Reinstall Scripture Pipelines.",
        )

    restored, failed, missing = _repair_group(entries, root, restore_when_absent)

    if failed:
        return Check(
            check_id,
            f"{label}: could not be repaired",
            Severity.ERROR,
            detail="Failed to restore: " + ", ".join(sorted(failed)),
            remedy=remedy,
        )
    if restored:
        return Check(
            check_id,
            f"{label}: {len(restored)} of {total} restored",
            Severity.WARNING,
            detail=(
                "Missing or changed, so sp restored them from the shipped version: "
                + ", ".join(sorted(restored))
            ),
            repaired=True,
        )
    if missing:
        return Check(
            check_id,
            f"{label}: {total - len(missing)}/{total} present",
            Severity.WARNING,
            detail="Missing: " + ", ".join(sorted(missing)),
            remedy=remedy,
        )
    return Check(check_id, f"{label}: all {total} present and unchanged", Severity.OK)


def run_doctor(
    sp_home: Optional[Path] = None,
    project_dir: Optional[Path] = None,
    claude_home: Optional[Path] = None,
) -> Report:
    """Inspect the machine, repair what sp owns, and return a Report.

    Args:
        sp_home: the ~/.sp directory. Defaults to _paths.sp_home().
        project_dir: the repository to check. Defaults to the working directory.
        claude_home: the ~/.claude directory. Defaults to Path.home() / ".claude".
    """
    sp_home = sp_home or _paths.sp_home()
    project_dir = project_dir or Path.cwd()
    claude_home = claude_home or Path.home() / ".claude"

    report = Report()
    add = report.checks.append

    catalog = managed_by_doctor()
    sp_entries = [e for e in catalog if e.scope is Scope.SP_HOME]

    # --- ~/.sp itself -------------------------------------------------------
    if sp_home.is_dir():
        add(Check("sp_home", f"{sp_home} exists", Severity.OK))
    else:
        sp_home.mkdir(parents=True, exist_ok=True)
        add(
            Check(
                "sp_home",
                f"{sp_home} was missing",
                Severity.WARNING,
                detail="No global resources were installed; sp restored the directory.",
                repaired=True,
            )
        )

    # --- disciplines, root files, skills ------------------------------------
    add(
        _group_check(
            "disciplines",
            "Conventions",
            [e for e in sp_entries if e.path.startswith("disciplines/")],
            sp_home,
            total=len(_shipped_names("sp/disciplines")),
        )
    )
    add(
        _group_check(
            "sp_root_files",
            "Root files",
            [e for e in sp_entries if "/" not in e.path],
            sp_home,
            total=len(_shipped_names("sp")),
        )
    )
    add(
        _group_check(
            "skills_installed",
            "Skills in ~/.sp",
            [e for e in sp_entries if e.path.startswith("skills/")],
            sp_home,
            total=len(_shipped_skill_names()),
        )
    )

    # --- project files sp owns ----------------------------------------------
    # Divergence only. A project file that is simply absent is sp init's business.
    project_entries = [
        e for e in catalog if e.scope is Scope.PROJECT and e.source is Source.CONSTANT
    ]
    present = [e for e in project_entries if (project_dir / e.path).exists()]
    if present:
        add(
            _group_check(
                "project_context",
                "Project files sp owns",
                present,
                project_dir,
                total=len(present),
                restore_when_absent=False,
                remedy="Run `sp init --update` in this project.",
            )
        )

    # --- can Claude Code actually see any skills? ---------------------------
    # ~/.sp/skills is NOT a location Claude Code reads. Skills only become invocable from
    # ~/.claude/skills/ or <repo>/.claude/skills/ (plan D1).
    project_skills = project_dir / ".claude" / "skills"
    personal_skills = claude_home / "skills"
    found: list[str] = []
    if project_skills.is_dir() and any(
        (p / "SKILL.md").exists() for p in project_skills.iterdir() if p.is_dir()
    ):
        found.append(".claude/skills (this project)")
    if personal_skills.is_dir() and any(
        (p / "SKILL.md").exists() for p in personal_skills.iterdir() if p.is_dir()
    ):
        found.append("~/.claude/skills (personal)")

    if found:
        add(
            Check(
                "skills_reachable",
                "Skills are where Claude Code reads them",
                Severity.OK,
                detail="Found in: " + ", ".join(found),
            )
        )
    else:
        add(
            Check(
                "skills_reachable",
                "No skills are where Claude Code can find them",
                Severity.ERROR,
                detail=(
                    "~/.sp/skills is not a location Claude Code reads. Slash commands such as "
                    "/load-context will not exist until skills are in .claude/skills."
                ),
                remedy="Run `sp init` in this project to copy them into .claude/skills/.",
            )
        )

    # --- project-side AI context -------------------------------------------
    ai_context = project_dir / "docs" / "ai-context"
    if ai_context.is_dir():
        names = sorted(p.name for p in ai_context.glob("*.md"))
        if names:
            add(
                Check(
                    "ai_context",
                    f"docs/ai-context/: {len(names)} file(s)",
                    Severity.OK,
                    detail=", ".join(names),
                )
            )
        else:
            add(
                Check(
                    "ai_context",
                    "docs/ai-context/ exists but is empty",
                    Severity.WARNING,
                    remedy="Run `sp init` in this project.",
                )
            )
    else:
        add(
            Check(
                "ai_context",
                "docs/ai-context/ is missing",
                Severity.WARNING,
                detail="This project carries no committed AI context.",
                remedy="Run `sp init` in this project.",
            )
        )

    # --- CLAUDE.md: informational only (D3-A) ------------------------------
    if (project_dir / "CLAUDE.md").exists():
        add(Check("claude_md", "CLAUDE.md present", Severity.OK))
    else:
        add(
            Check(
                "claude_md",
                "No CLAUDE.md in this project",
                Severity.INFO,
                detail=(
                    "Not required. It is gitignored by convention, so a fresh clone never has "
                    "one; committed context lives in docs/ai-context/."
                ),
            )
        )

    # --- project registration ----------------------------------------------
    projects_dir = sp_home / "projects"
    registered = {p.stem for p in projects_dir.glob("*.yaml")} if projects_dir.is_dir() else set()
    if project_dir.name in registered:
        add(Check("registered", f"Project '{project_dir.name}' is registered", Severity.OK))
    else:
        add(
            Check(
                "registered",
                f"Project '{project_dir.name}' is not registered in ~/.sp/projects/",
                Severity.WARNING,
                remedy="Run `sp init` in this project.",
            )
        )

    return report


def doctor_command(project_dir: Optional[Path] = None) -> int:
    """CLI entry point. Prints the report and returns an exit code."""
    report = run_doctor(project_dir=project_dir)
    print(report.render())
    return report.exit_code
