#!/usr/bin/env python3
"""Compare the shared set against Human at the Helm, and copy it over on request.

Plan: `project/plans/design-hath-parity.md` §7 step 6, ruling H3-B — a sync script *"run
deliberately, with a test that fails when the two sides diverge unexpectedly."* The test is
`tests/test_hath_sync.py`; this is the script.

**Reporting is the default; copying takes a flag** (ruling D8-A). Running this tells you
what differs and writes nothing. `--apply` is the second, deliberate act.

    hatch run python tools/sync_hath.py                 # report; writes nothing
    hatch run python tools/sync_hath.py --apply         # copy, then refresh the record
    hatch run python tools/sync_hath.py --refresh-record  # hashes only; HATH untouched

**What it will not do.** A file whose record entry says it deliberately differs is never
copied, in either direction. `audit-code` is not in the shared set at all (H4-A), so this
script cannot create a counterpart for it in HATH.

**Where the shared set comes from.** The classification constants in
`tests/test_portable_skills.py` and `tests/test_portable_disciplines.py` — the same ones the
guards enforce. Importing them from the tests is deliberate: a copy of "which skills are
shared" living here as well is precisely the second hand-kept list that left three
disciplines unshipped for months (#204).
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tests.test_hath_sync import (  # noqa: E402
    DEFAULT_HATH_CLONE,
    HATH_ENV_VAR,
    RECORD_PATH,
    _derived_shared_set,
    _hath_root,
    _source_path,
    _target_path,
)

# The script owns this header and rewrites it with the file. Anything a human needs to say
# about a particular file goes in that entry's `ruling` field, which is data and survives a
# regeneration — a comment beside an entry would not.
HEADER = """\
# The state of the set shared with Human at the Helm (human-at-the-helm#1, plan §7 step 6).
#
# GENERATED BY tools/sync_hath.py. Hashes and statuses are rewritten by that script; the
# `ruling` and `hath_only` texts are written by hand and preserved across regenerations.
#
# Ruling H3-B: LLMFlow is upstream, and the two sides may only differ where a ruling says
# so. `tests/test_hath_sync.py` enforces this file against what the package actually ships,
# so it runs on CI where no clone of HATH exists, and additionally against the clone when
# one is present (ruling D7-C).
#
# ---------------------------------------------------------------------------
# Fields
#
#   set      skills | disciplines | root   (which shipped directory the file comes from)
#   name     file or skill directory name
#   sha256   hash of THIS repository's copy, at the last refresh
#   status   identical  the two copies must match byte for byte
#            differs    they are allowed to differ, and `ruling` says why
#   ruling   the decision permitting a difference. Required when status is `differs`;
#            quote the Captain rather than paraphrasing.
#
# `hath_only` lists what Human at the Helm ships that this repository does not — its own
# skills and the essays its README calls the disciplines proper. Without it the live check
# would report HATH's own material as unexplained. Each entry carries a `path` and a `note`
# saying what it is; both are fields rather than comments, because a regeneration of this
# file keeps data and discards comments.
# ---------------------------------------------------------------------------
"""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_existing() -> dict:
    if not RECORD_PATH.is_file():
        return {}
    return yaml.safe_load(RECORD_PATH.read_text(encoding="utf-8")) or {}


def _entry_stub(key: str) -> dict:
    set_id, name = key.split("/", 1)
    return {"set": set_id, "name": name}


def _build(existing: dict) -> list[dict]:
    """One entry per shared file, preserving any ruling already recorded for it."""
    prior = {f"{e['set']}/{e['name']}": e for e in (existing.get("files") or ())}
    entries = []
    for key in sorted(_derived_shared_set()):
        entry = _entry_stub(key)
        entry["sha256"] = _sha256(_source_path(entry))
        was = prior.get(key, {})
        entry["status"] = was.get("status", "identical")
        if was.get("ruling"):
            entry["ruling"] = was["ruling"]
        entries.append(entry)
    return entries


def _write_record(existing: dict, entries: list[dict]) -> None:
    body = {
        "version": 1,
        "hath_clone_default": existing.get("hath_clone_default", DEFAULT_HATH_CLONE),
        "files": entries,
        "hath_only": existing.get("hath_only") or [],
    }
    RECORD_PATH.write_text(
        # allow_unicode: the rulings quote the Captain, and an em dash escaped to —
        # makes a hand-written sentence unreadable in the file it was written into.
        HEADER
        + "\n"
        + yaml.safe_dump(body, sort_keys=False, width=96, allow_unicode=True),
        encoding="utf-8",
    )


def _report(entries: list[dict], hath: Path | None) -> list[dict]:
    """Print a line per shared file; return the entries that need copying."""
    print(f"Shared with Human at the Helm: {len(entries)} files")
    print(f"  from  {_source_path(entries[0]).parent.parent}")
    print(f"  to    {hath if hath else '(no clone found)'}\n")

    stale: list[dict] = []
    for entry in entries:
        key = f"{entry['set']}/{entry['name']}"
        if hath is None:
            print(f"  {'recorded':10}  {key}")
            continue

        target = _target_path(entry, hath)
        if not target.is_file():
            print(f"  {'MISSING':10}  {key}  -> {target}")
            stale.append(entry)
        elif _sha256(target) == entry["sha256"]:
            print(f"  {'same':10}  {key}")
        elif entry["status"] == "differs":
            first = (entry.get("ruling") or "").strip().splitlines()[0:1]
            print(f"  {'ruled':10}  {key}  ({first[0] if first else 'NO RULING RECORDED'})")
        else:
            print(f"  {'DIVERGED':10}  {key}")
            stale.append(entry)

    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="copy this repository's copy over HATH's where they diverge, then refresh the record",
    )
    parser.add_argument(
        "--refresh-record",
        action="store_true",
        help="rewrite the record's hashes from what this repository ships; HATH untouched",
    )
    args = parser.parse_args(argv)

    existing = _load_existing()
    entries = _build(existing)
    hath = _hath_root()

    if hath is None and args.apply:
        print(
            f"No Human at the Helm clone found. Set ${HATH_ENV_VAR}, or clone it to "
            f"{existing.get('hath_clone_default', DEFAULT_HATH_CLONE)}.",
            file=sys.stderr,
        )
        return 2

    stale = _report(entries, hath)

    if args.apply and stale:
        print()
        for entry in stale:
            source, target = _source_path(entry), _target_path(entry, hath)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            print(f"  copied     {entry['set']}/{entry['name']}  -> {target}")

    if args.apply or args.refresh_record:
        _write_record(existing, _build(_load_existing()))
        print(f"\nRecord refreshed: {RECORD_PATH.relative_to(REPO_ROOT)}")
    elif stale:
        print(
            f"\n{len(stale)} file(s) differ with no ruling. Re-run with --apply to copy "
            "them, or record the ruling that permits the difference."
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
