#!/usr/bin/env python3
"""Generate `project/plans/README.md` — an index of design and plan documents.

Why this exists: `project/plans/` holds 25+ documents at different stages. Every one
already declares a status, but a reader facing the bare directory has to open each file
to learn which are authoritative, which are historical, and which were never built. An
LLM has it worse: `docs/ai-context/index.md` maps topics to files and does not mention
this directory at all.

This tool is repo-local by design. It lives in `tools/` rather than `src/llmflow/` so it
is not part of the installed package, and it writes only inside `project/plans/`, so
nothing it produces can reach a project created by `sp init`.

Usage:
    hatch run python tools/update_plans_index.py          # write the index
    hatch run python tools/update_plans_index.py --check  # exit 1 if out of date

Convention: rule `file-organisation` — plans live in `project/plans/`, named `design-*.md`
or `plan-*.md`.
Dates are deliberately absent: `~/.sp/disciplines/project-tracking.md` puts dates on
items rather than in filenames or indexes, and git history is the audit trail.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLANS_DIR = REPO_ROOT / "project" / "plans"
INDEX_PATH = PLANS_DIR / "README.md"
GENERATED_MARKER = "<!-- Generated by tools/update_plans_index.py -->"

#: Matches `**Status:** …`, `## Status: …`, `Status: …`.
_STATUS_RE = re.compile(r"^\s*(?:#{1,3}\s*)?\*{0,2}status\*{0,2}\s*:\s*(.+)$", re.IGNORECASE)

#: Two- and three-digit issue references only. Single digits are excluded deliberately:
#: these documents cite cross-repository issues such as `human-at-the-helm#1`, and a
#: bare `#1` in this repository's index would be wrong more often than right.
_ISSUE_RE = re.compile(r"#(\d{2,3})\b")

#: How much of a status line the table carries before eliding.
_STATUS_WIDTH = 96


@dataclass
class Doc:
    path: Path
    status: str = ""
    issues: list[int] = field(default_factory=list)

    @property
    def name(self) -> str:
        return self.path.name


def _clean(text: str) -> str:
    """Reduce a status line to one table cell: no emphasis, no pipes, one line."""
    text = re.sub(r"\*\*|__|`", "", text)
    text = " ".join(text.split())
    text = text.replace("|", "\\|")
    if len(text) > _STATUS_WIDTH:
        cut = text[:_STATUS_WIDTH].rsplit(" ", 1)[0]
        text = f"{cut} …"
    return text


def parse_doc(path: Path) -> Doc:
    """Read a plan document's declared status and the issues it names."""
    doc = Doc(path=path)
    try:
        body = path.read_text(encoding="utf-8")
    except OSError:
        return doc
    for line in body.splitlines()[:40]:
        m = _STATUS_RE.match(line)
        if m:
            doc.status = _clean(m.group(1))
            break
    doc.issues = sorted({int(n) for n in _ISSUE_RE.findall(body)})
    return doc


def render_index(paths: list[Path]) -> str:
    """Render the index. Deterministic: sorted by filename, no dates."""
    docs = [parse_doc(p) for p in sorted(paths, key=lambda p: p.name)]
    lines = [
        GENERATED_MARKER,
        "# Design and Plan Documents",
        "",
        "Regenerate with `hatch run python tools/update_plans_index.py`. Each document"
        " declares its own status; this table collects them so the directory can be read"
        " at a glance.",
        "",
        "**Status is authored, not inferred.** A document saying *Implemented — historical"
        " record* describes why code looks the way it does; one saying *Proposed* has not"
        " been approved and is not authorization to build. Where a document and the code"
        " disagree, neither wins automatically — ask.",
        "",
        "| Document | Status | Issues |",
        "| --- | --- | --- |",
    ]
    for d in docs:
        issues = " ".join(f"#{n}" for n in d.issues) if d.issues else "—"
        status = d.status or "**no status declared**"
        lines.append(f"| [{d.name}]({d.name}) | {status} | {issues} |")
    lines += [
        "",
        f"{len(docs)} documents.",
        "",
    ]
    return "\n".join(lines)


def _docs() -> list[Path]:
    return sorted(p for p in PLANS_DIR.glob("*.md") if p.name != "README.md")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the index is stale")
    args = ap.parse_args(argv)

    expected = render_index(_docs())
    current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else None

    if args.check:
        if current == expected:
            print(f"✅ {INDEX_PATH.relative_to(REPO_ROOT)} is current")
            return 0
        print(f"❌ {INDEX_PATH.relative_to(REPO_ROOT)} is out of date")
        print("   💡 Regenerate: hatch run python tools/update_plans_index.py")
        return 1

    if current == expected:
        print(f"✅ {INDEX_PATH.relative_to(REPO_ROOT)} already current")
        return 0
    INDEX_PATH.write_text(expected, encoding="utf-8")
    print(f"✅ wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
