#!/usr/bin/env python3
"""Refresh `docs/ai-context/sp/rules.md` from `data/ai-rules.yaml`.

Reduced to the rules on 2026-08-25 (#210, #214). This script used to write three documents.
Two of them are now written by the file catalog, and the lists it kept in order to write them
were the defect:

- **`sp/index.md`** is `source: derived` in `data/file-catalog.yaml`, rendered from each entry's
  `purpose:`. This script wrote the same path from an 11-row Python tuple, so which document a
  reader got depended on which generator ran last — the same "one filename, two documents"
  failure #210 was opened to remove.
- **`sp/overview.md`** is `source: constant` in the catalog and was likewise written here.

Three hand-maintained tuples went with them: an index table, an overview reading list, and a
third list of the same paths again — 25 rows describing this repository's own documents. The
Captain, on why that shape is wrong: *"having a separate catalog in a Python code is (1) a
violation of our declarative principles and (2) a second source of truth. Seems wrong to me."*

Their content was this repository's own map, which is project-half content, and it is now
hand-authored at `docs/ai-context/project/index.md` — the way every project writes its own map.
It cannot be generated: *"we can't know what files a project has created in advance."*

What remains follows the pattern the rules already used and that the rest should have: one
source, `data/ai-rules.yaml`, read through `llmflow.ai_rules` by both renderers — this one and
`cli_utils.ai_rules_doc()`. Recorded at `cli_utils.py:975`, it ended the state where *"which
rules a project was held to depended on which generator last ran."*
"""
from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from llmflow.ai_rules import render_rules

REPO_ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = REPO_ROOT / "docs" / "ai-context" / "sp" / "rules.md"


def _build_rules_content() -> str:
    # Rendered by llmflow.ai_rules, not formatted here. Building the list locally was how
    # the `note:` fields silently failed to appear in this document while appearing in the
    # copy `sp init` writes — one source of rules, two renderers, same defect one level down.
    # Dedent the frame before substituting the rules, not after. `dedent` takes the common
    # leading whitespace of every line, so interpolating text whose own lines are unindented
    # makes that prefix empty and leaves the frame's indentation in the output — which turned
    # the document's headings into indented code blocks (#230).
    frame = dedent(
        """\
        <!-- Generated by tools/update_ai_context.py -->
        # AI Assistant Rules

        These guardrails apply to any language model collaborating on Scripture Pipelines tasks.

        {rules}

        Pin these rules alongside `overview.md` and `index.md` when starting an AI session so
        expectations are clear from the outset.
        """
    )
    return frame.format(rules=render_rules()).strip() + "\n"



def _write_file(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    new_content = content if content.endswith("\n") else content + "\n"
    if path.exists():
        if path.read_text(encoding="utf-8") == new_content:
            return False
    path.write_text(new_content, encoding="utf-8")
    return True



def main() -> None:
    if _write_file(RULES_PATH, _build_rules_content()):
        print(f"Updated {RULES_PATH.relative_to(REPO_ROOT)}")
    else:
        print("Rules document already up to date")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover
        print(f"Error while updating the rules document: {exc}", file=sys.stderr)
        sys.exit(1)
